### ISSUE TITLE
Series specific overrides Add treshold option "IS BELOW"

### ISSUE THREAD

**Issue by fatslimjoe** [jdbranham/grafana-diagram#102]
Hi Team,

I have a little question if thats ok by U :) and it is regarding Series Specific Overrides of diagram plugin from picture below:

![image](https://user-images.githubusercontent.com/7080575/45032857-15d73680-b053-11e8-8215-d66d8bcd6103.png)

Is it possible to add in the treshold field condition "IS BELOW" not only "IS ABOVE" what is default?

Kind regards

**Comment by jdbranham** [comment]
Thanks for the feedbacl @fatslimjoe 
Could you explain your use-case a bit?
