### ISSUE TITLE
Feature: Support replacements

### ISSUE THREAD

**Issue by RichiH** [jdbranham/grafana-diagram#11]
It would be quite useful to be able to replace text with Prometheus label values. I.e. instead of `_my_prom_query_[name]`, I would prefer to be able to write `_my_prom_query_[{{instance}}]`.

**Comment by coussej** [comment]
Somewhat related: The singlestat panel supports value mappings, for example 0 = Stopped, 1 = Running. It would be useful to have a similar function so that instead of a value you can show a mapped text below the nodes.

**Comment by kfox1111** [comment]
Or its value. so you could label network links with a box with its gb/s value for example.
