### ISSUE TITLE
[Grafana] Diagram Plugin could have like Picture in Picture (object redirect/ link to a graph)?

### ISSUE THREAD

**Issue by fchiorascu** [jdbranham/grafana-diagram#112]
Hi,

If I have a Diagram in Grafana based on a component for example, servers architecture and when I'm doing a click for an object represented by 3 servers/cluster is there a way of link/redirect or something to the graph for that components or cluster like an image that is opening at the click on the diagram object or redirect/link on the bottom of the page to the graph of that component.
Plugin: jdbranham-diagram-panel @ 1.4.4
Grafana: grafana-5.3.1-1.x86_64

Kind Regards,
Florian

**Comment by iba12** [comment]
Hello,
I came here to ask for this as a feature, on a broader (or if you want, more specific) scope; the addition of a LINK capability for each element in a graph. As Florian said, if a specific element in my graph represents a cluster, he would like that element to be clickable to point to an image, but I'd say, just let us create a link, and what that link is doesn't matter (or should not matter). if we want to load an image, or a URL or another grafana dashboard, I just wish I can have a link.

Is this possible at the moment? For example, from this:

graph LR
Transcode --- QC
QC --- Encryption
Encryption --- Publish

to something that might look like this:

graph LR
Transcode<<URL>> --- QC<<GraphanaDashboard>>
QC --- Encryption<<Image file>>
Encryption --- Publish<<FTP session>>

with all of them being links of some kind. 

If that is of any concequence, i'm mostly interested in having the "other graphana dashboard link" most of all.

Regards,
Ioannis

**Comment by jdbranham** [comment]
This is possible, like @iba12 mentioned - 

> Edit: I discovered that the below request actually already is possible, if one follows the graph entities with a [<a href="link">text</a>] block. So it would look like Transcode[<a href='www.host.com'>TranscodeEntinty</a>] and it would take data from a Transcode metric alias and present a link which is clickable with the text TranscodeEntity]
