### ISSUE TITLE
Rendering issue when changing value for templating variables

### ISSUE THREAD

**Issue by sofiedc** [jdbranham/grafana-diagram#113]
After changing the value for a templating variable, some of the diagram panels are collapsed (height 0).

![grafana-diagram-refresh-issue](https://user-images.githubusercontent.com/5428785/49004580-cccfe380-f164-11e8-9ac6-3daee219c06e.JPG)

Only after performing a refresh (F5), the issue is gone

**Comment by xenthik** [comment]
I am new to the grafana-diagram plugin, How did you added 'xCode' square box ?

**Comment by jdbranham** [comment]
@sofiedc does this happen with the latest version?

**Comment by SaSc0803** [comment]
@xenthik 
you can add this box by defining a subgrapf like this:
<pre>
graph LR
example1
subgraph box
example2
example3
end
example1 --> example2
example1 --> example3
</pre>
it should look something like this:
![Unbenannt](https://user-images.githubusercontent.com/51954354/72349749-65b11d80-36dd-11ea-97ce-a3a4dcd4f400.JPG)

**Comment by SaSc0803** [comment]
@sofiedc 
Hi,
i had the same issue.
Did you set the value like this?:
![Unbenannt](https://user-images.githubusercontent.com/51954354/72350298-7615c800-36de-11ea-8c75-094489e6a2a5.JPG)
![Unbenannt](https://user-images.githubusercontent.com/51954354/72350343-92196980-36de-11ea-83a3-98129b934748.JPG)

or like this?:
![Unbenannt](https://user-images.githubusercontent.com/51954354/72350478-cc830680-36de-11ea-9b85-6c0c2a7396c0.JPG)

I had the same render issues when doing it the first way.
The second worked just fine for me.

**Comment by sofiedc** [comment]
We're now on grafana v5.1.3, and version 1.4.5 of the diagram plugin, and no longer seem to run into the issue.

our queries look like this:

![image](https://user-images.githubusercontent.com/5428785/72373437-9490b900-3708-11ea-82b9-42456194ca2d.png)

**Comment by sofiedc** [comment]
closing issue since it no longer occurs in the latest version
