### ISSUE TITLE
Panel Height Clipped

### ISSUE THREAD

**Issue by CME64** [jdbranham/grafana-diagram#119]
after grafana v5.4 the panel's content is clipped vertically
it's certainly a bug and is not affecting other plugins
note: it used to work for grafana 5.3 just fine with the exact same settings

here is a screenshot

![image](https://user-images.githubusercontent.com/4494649/51538843-5f3dec00-1e63-11e9-90c6-d0f241953a4b.png)

edit
I may fix the bug if you just point me to the right direction. I found out that the height of the panel's custom container is fixed and it works fine if it was filled with 100% instead of **px defined inline.

**Comment by CME64** [comment]
solved it by commenting this line in diagramControl
`elem.css('height', ctrl.height + 'px');`
apparently grafana is setting the height to 100% but it's overridden by the inline style generated by this line

**Comment by CME64** [comment]
should be reflected in the Repo before closure ,, sorry

**Comment by jdbranham** [comment]
Thank you @CME64 this is resolved in v1.4.5 
A pull request is opened to update the Grafana plugin repo -
https://github.com/grafana/grafana-plugin-repository/pull/323

**Comment by jdbranham** [comment]
https://github.com/jdbranham/grafana-diagram/blob/72520fc3a5e8f5be4c452c8f0568540470e74e18/src/diagramControl.js#L631
