### ISSUE TITLE
Overlap issue for value box and lose color when refreshing webpage

### ISSUE THREAD

**Issue by LiangRao** [jdbranham/grafana-diagram#120]
Hi, I met some problems with Diagram panel.

1. The value box overlaps the text box.
2. Every time I refresh the web page, the color will disappear.

![screen shot 2019-01-30 at 1 23 21 pm](https://user-images.githubusercontent.com/25234631/52003426-7ba8dc80-2492-11e9-8434-a526a781ac75.png)
![screen shot 2019-01-30 at 1 23 37 pm](https://user-images.githubusercontent.com/25234631/52003427-7ba8dc80-2492-11e9-937e-1d6da62d2b0c.png)

Are there any ideas to solve it?
Thanks!

**Comment by jdbranham** [comment]
Thanks @LiangRao 
The color/refresh issue has been resolved in the latest version. It should be linked to the Grafana plugin repository soon.
You can check out this repository directly to your Grafana plugins directory if you dont want to wait.

https://github.com/grafana/grafana-plugin-repository/pull/323
