### ISSUE TITLE
Cannot use classDef

### ISSUE THREAD

**Issue by AbdulRahmanAlHamali** [jdbranham/grafana-diagram#121]
classDefs are ignored in the flowchart graphs. This could be fixed either by setting `cloneCssStyles` to `true` (I am not sure why it is set to false), or by upgrading to a newer version of mermaidjs

**Comment by jdbranham** [comment]
There was a problem with this in an earlier version, but it seems to work fine now.
Enabled now - 
https://github.com/jdbranham/grafana-diagram/commit/70f3304f0c7958dfc67a50893645744dcfda7097

**Comment by jdbranham** [comment]
graph definition -
```
graph LR
    A-series(Start)-->id2(Stop)
    style A-series fill:#f9f,stroke:#333,stroke-width:4px
    style id2 fill:#ccf,stroke:#f66,stroke-width:2px,stroke-dasharray: 5, 5
```

![image](https://user-images.githubusercontent.com/2660839/60747308-f0a0a680-9f49-11e9-801b-4fc2970a9abd.png)
