### ISSUE TITLE
Multiple Datasource

### ISSUE THREAD

**Issue by fadjar340** [jdbranham/grafana-diagram#124]
Is it possible to have multiple datasource in single diagram? I need to show the Uptime and CPU load in single diagram, but with current version, it can not work.
I use grafana 6.2.0Beta

Regards,
Fadjar Tandabawana

**Comment by briangann** [comment]
you can use multiple datasources - the plugin just uses metrics provided by the queries created, and those can be from different datasources.

**Comment by fadjar340** [comment]
Thank you....
