### ISSUE TITLE
Is this plugin compatible with PRTG Datasource ?

### ISSUE THREAD

**Issue by LiamEponym** [jdbranham/grafana-diagram#126]
Hi everyone,

I'm pretty new to Grafana and this diagram plugin and I would like to know if this plugin can work with PRTG Datasource, I tried to find it on my own but I can't use my queries in the visualization...
Am I missing something ?

**Comment by jdbranham** [comment]
Hi @LiamEponym -
I've never tried with PRTG datasource, but I might be able to help. 
Is there an error message occurring when you try?

**Comment by jdbranham** [comment]
Since the data shape is an abstraction, it should work with any datasource.
