### ISSUE TITLE
Composite Metrics only using the first metrics

### ISSUE THREAD

**Issue by brucec64** [jdbranham/grafana-diagram#127]
I'm trying to create a composite metric for a metric with values 2,3 or 4. However, the composite metric will display based on the first metric only. When I change the order of the metric, the composite metric now will display based on the new first metric. This occurs regardless of the value - it does not matter if the value is 2,3 or 4. Thresholds are set to 0,2,3,4.

I can come up with a workaround by creating composites at the query level. However, the metric displayed does not have meaning. Is there a way to suppress the "worst" metric in the diagram?

**Comment by zsabin** [comment]
I came across this same issue. It seems to be related to the number of colors you are using for your thresholds. 3 colors works fine. Greater than or less than three fails to capture the state of any but the first metric in the composite.

**Comment by jdbranham** [comment]
I'm making a change to how this works. Can someone check it out?
I want to see if it's intuitive enough for no explanation. If not, I'll make some adjustments.
Also, please let me know if this breaks any of your use-cases.

Thanks!

**Comment by dykyy** [comment]
Hi.
I faced same issue July 5th about 2 hours before you made new commit with the fix.
Unfortunately I can not  verify the fix because if I download and put new files that were changed in the commit instead of old (total 6 files) my dashboard stops working with "Cannot read property 'firstChild' of null".
When I reinstall version 1.5.0 plugin is working, diagram is showing worst value (correct) **but** showing only 2 colors instead of 3 colors  for 2 thresholds. I'm using thresholds '60,80' for percent format. On the diagram values before 80 are marked with the first color, after 80 - in second.

Workaround is using "Gradient colors" which is fine for me.

**Comment by gianlorenzop** [comment]
Hi, I tested latest version of this plugin on grafana 6.0.2 with composite metrics (elasticsearch query) with only 3 colors and with or without threshold override and it uses only the first metric (even if correct value is present in legend).
For the use i need to do of this plugin this bug makes it useless! Please fix it thanks so much

**Comment by jdbranham** [comment]
@gianlorenzop
Hi!
Specifically which version of the plugin do you have installed?

**Comment by gianlorenzop** [comment]
@jdbranham sorry, i was sure it was the latest version but you had already released a new one(i was using 1.4.5), I updated the plugin to 1.6.1 and now seems to work well, except for threshold override, it changes color even if the overrided metric is in the green threshold (for global value this value is critical) thanks again, and sorry again

**Comment by jdbranham** [comment]
No worries! I've got to revisit the overrides for composites. I disabled some things to simplify the code.

**Comment by Tetraneon** [comment]
Hi,
Thanks for this very useful plugin but I got this error too...
Everything goes well after install : I can edit the graph but... after reading the Mairmaid doc, I try hexagon node : 
```
graph LR
    id1{{This is the text in the box}}
```
A error appear 
`Cannot read property 'firstChild' of null`

Here is the details : 
```
TypeError: Cannot read property 'firstChild' of null
    at Object.render (https://my-domain.net:3000/public/plugins/jdbranham-diagram-panel/libs/mermaid/dist/mermaid.js:113806:26)
    at DiagramCtrl.renderDiagram (https://my-domain.net:3000/public/plugins/jdbranham-diagram-panel/diagramControl.js:454:24)
    at DiagramCtrl.updateDiagram (https://my-domain.net:3000/public/plugins/jdbranham-diagram-panel/diagramControl.js:478:22)
    at DiagramCtrl.onDataReceived (https://my-domain.net:3000/public/plugins/jdbranham-diagram-panel/diagramControl.js:255:18)
    at s.emit (https://my-domain.net:3000/public/build/vendor.dfabdd44b3be44288eac.js:86:11360)
    at t.emit (https://my-domain.net:3000/public/build/app.dfabdd44b3be44288eac.js:1:181443)
    at DiagramCtrl.e.handleQueryResult (https://my-domain.net:3000/public/build/app.dfabdd44b3be44288eac.js:22:485969)
    at https://my-domain.net:3000/public/build/vendor.dfabdd44b3be44288eac.js:130:92198
    at https://my-domain.net:3000/public/build/vendor.dfabdd44b3be44288eac.js:130:92295
    at l.$digest (https://my-domain.net:3000/public/build/vendor.dfabdd44b3be44288eac.js:130:97589)
```
After transforming the hex node in an other one, the error stays. I had to remove and reinstall the plugin...
