### ISSUE TITLE
Show label of worst metric in composites

### ISSUE THREAD

**Issue by ffo** [jdbranham/grafana-diagram#129]
Hi.

I am trying to use composites to visualize the worst of a set of metrics. It seems that for composites only the value of the worst metric is shown in the diagram, but not the name of the metric it self: 
![panel](https://user-images.githubusercontent.com/788381/60009496-45087400-9676-11e9-8e17-1a97194ead9c.png)
As I hide the legend in my use case, it is difficult to see which metric is actually causing the problem.

In diagramControl.js:477 the code that displays the label of the worst metric as a prefix is commented out:

`// currentWorstSeries.valueFormatted = currentWorstSeriesName + ': ' + currentWorstSeries.valueFormatted;`

Was this change made by intention or to disable the feature? Is there any other way to get the metric name as a prefix of the value?

Regards

Frank

P.S.: Thanks for this plugin. A perfect tool to visualize the current state of our infrastructure.

**Comment by jdbranham** [comment]
Hi @ffo !
Which version of the plugin are you using?

**Comment by ffo** [comment]
I used Version 1.5.0 from your master branch.

btw: I think I forgot to attach the panel configuration, when I created the request:
[panel.txt](https://github.com/jdbranham/grafana-diagram/files/3361475/panel.txt)

**Comment by jdbranham** [comment]
Check out the latest version and let me know if it works.
Thanks for the feedback!

**Comment by ffo** [comment]
The label is shown now. But the layout seems to be broken and if I activate "show lowest value" for a composite, the right value with the wrong label is shown:

![grafana_diagram](https://user-images.githubusercontent.com/788381/60738948-51d37480-9f60-11e9-9842-45c5e66b56b2.png)

**Comment by jdbranham** [comment]
I'm not able to reproduce with your panel json...
It might be cached CSS causing the trouble. Can you clear the browser cache to see if there's any change?

**Comment by ffo** [comment]
The layout issue occurs only on Firefox and browsers derived from it. Chrome does not show the issue.

Anyway, it always shows the label of the last metric even if this metric is not the worst one.

F.

**Comment by jdbranham** [comment]
Ok, I fixed the naming bug, but the sizing is a bit trickier.
The dimensions of the nodes are calculated before the metric values are added to the diagram, so things get a bit jumbled after modifying the text content, particularly in Firefox.

**Comment by ffo** [comment]
I also see the correct labels now, if I use your grafana-6x branch. Thanks! 

Also the main label is no longer truncated if I use Firefox the main label is not truncated any longer.
![grafana_diagram_composite](https://user-images.githubusercontent.com/788381/60772407-34d0aa00-a0f6-11e9-88a9-51323066ce29.png)

As far as I remember the truncate of worst metric label + value in composites was already there in the old version. I worked around this by keeping an eye on the length of my composite labels and added the possibility to specify [labels for the metrics of a composite](/ffo/grafana-diagram/tree/compositelabels) in my fork. Anyway, this is a different topic that has nothing to do with this issue. If you like the feature I would open an issue and create a pull request.

F

**Comment by jdbranham** [comment]
Thanks @ffo ! I'm always interested in PRs =]

Also, all the editors could use some work, especially with Grafana 6x.
I opened issue #133 to start tracking some changes there.
