### ISSUE TITLE
Bug?: No way to insert subgraphs

### ISSUE THREAD

**Issue by RichiH** [jdbranham/grafana-diagram#13]
This is more on the Grafana side, but I am unable to enter subgraphs as per https://knsv.github.io/mermaid/#subgraphs as Grafana always eats my tab. Is there a way around this? 

Also tagging @bergquist as he might have input from the Grafana side.

**Comment by jdbranham** [comment]
![image](https://cloud.githubusercontent.com/assets/2660839/19402253/bc7513c0-9225-11e6-868b-bd774017beb4.png)

**Comment by RichiH** [comment]
Thanks!

Richard

Sent by mobile; excuse my brevity.
