### ISSUE TITLE
mermaid update

### ISSUE THREAD

**Issue by holiiveira** [jdbranham/grafana-diagram#130]
Would it be possible to upgrade the mermaid version?

[6.0.0](https://github.com/jdbranham/grafana-diagram/blob/master/bower.json#L18) to [8.1.0](https://github.com/knsv/mermaid/releases/tag/8.1.0)

**Comment by jdbranham** [comment]
Done!

https://github.com/jdbranham/grafana-diagram/blob/ec80ebe0d0fa6c9dea615c51d4dacf2cc0721c6f/package.json#L53

**Comment by holiiveira** [comment]
@jdbranham do you expect to release a new version when?

**Comment by jdbranham** [comment]
It may be a few days. There are a lot of other changes in the branch that I'd like to have a few people test before an official release.
You can download and install the plugin manually though...

Unzip to your Grafana data/plugins directory -
https://github.com/jdbranham/grafana-diagram/archive/master.zip

**Comment by sastorsl** [comment]
Did you get around to creating a new release?
