### ISSUE TITLE
Thresholds not working as expected

### ISSUE THREAD

**Issue by zsabin** [jdbranham/grafana-diagram#135]
Threshold ranges are working differently after I upgraded to version 1.6.1 and its very confusing. The threshold values still represent lower bounds, but it seems that the first number in the threshold is completely ignored. This requires me to add a third threshold value if I want three severity levels. 

So for instance, previously the threshold 1,2 would give me three levels (x <1, 1 <= x <2, x >=2). Now if I want the same three levels I would need to use a range like 1,1,2, where that first number could be anything. I should note that I'm using discrete colors, not gradients.

**Comment by jdbranham** [comment]
Thanks @zsabin - I'll take a look at this.

**Comment by jdbranham** [comment]
Thresholds and composites have been completely rewritten in the new version.  
Closing this issue - please re-open if needed.
