### ISSUE TITLE
Coloring links

### ISSUE THREAD

**Issue by elvarb** [jdbranham/grafana-diagram#14]
Would be very nice if you could modify the styling of links and arrows when a threshold is hit

for example

linkStyle 3 stroke:#ff3,stroke-width:4px;

**Comment by RichiH** [comment]
To expand on this, per-edge thresholds would allow for visualizing different link speeds in one diagram. Obviously, it's also possible to precompute a percentage and use common thresholds over all edges.

**Comment by jdbranham** [comment]
![image](https://cloud.githubusercontent.com/assets/2660839/20502835/82c2f02c-b005-11e6-9118-bef3319155a6.png)

    graph TB
    Web1 --Firewall--> App1 
    Web2 --Firewall--> App1


I've added a patch that colors the edge labels, but it will be a while before I can modify the actual edge styling [thickness/color, etc...]

**Comment by jdbranham** [comment]
Fixed!
