### ISSUE TITLE
Grafana-diagram plugin will support ElasticSearch Datasource

### ISSUE THREAD

**Issue by swethapaneet** [jdbranham/grafana-diagram#140]
HI,
I have requirement of creating the network panel in grafana..So i opt for grafana-diagram,but when i'm trying to  create a grafana-diagram in elasticSearch it was showing a error 
 Cannot read property 'firstChild' of null
    at Object.render (mermaidAPI.js:378)
    at DiagramCtrl.renderDiagram (diagramControl.js:347)
    at successCallback (diagramControl.js:364)
    at angular.js:17051
    at angular.js:17095
    at c.$digest (angular.js:18232)
    at c.$apply (angular.js:18531)
    at angular.js:18832
    at p (angular.js:6362)
    at angular.js:6642 "Possibly unhandled rejection: {}

Pls let  me know  whether grafana -diagram will support the elasticserach datasource

**Comment by jdbranham** [comment]
It hasn't been tested with Elasticsearch before.
Which version of Grafana, and which version of Elasticsearch are you working with?

**Comment by jdbranham** [comment]
The `firstChild of null` was a bug that should be resolved now. 
Also, I've verified it works with Elasticsearch datasource - 

![image](https://user-images.githubusercontent.com/2660839/79718792-87084380-82a2-11ea-90e2-9aa18146a865.png)
