### ISSUE TITLE
Unable to use Diagram

### ISSUE THREAD

**Issue by TJ-C** [jdbranham/grafana-diagram#142]
Could you clarify the correct syntax to use to build up a LR diagram please, as every time I try to edit the content I get an error?
![Screenshot 2020-01-12 at 18 42 19](https://user-images.githubusercontent.com/7023367/72223857-7e99c180-356b-11ea-83f9-db8a961fb326.png)

**Comment by briangann** [comment]
mermaid syntax doesn't like the empty ```(())```

this works:

```
graph LR
sol(Solar) -- "@sol" --> mix((placeholder))
grid[Grid] -- "@grid" --> Y
Y -- "@conLessImm" --> con(Home)
mix -- "@ims" --> ims((Water Tank))
mix -- "@bat" --> bat(Battery)
mix --> Y((placeholder))
```
