### ISSUE TITLE
Mapping-Rule for multiple elements

### ISSUE THREAD

**Issue by SaSc0803** [jdbranham/grafana-diagram#143]
Hi,
i'm testing grafana with your plugin on my network combined with my icinga and influxdb.
I have created a diagram with all hosts and their states (if the host has a ping the value is 0, if not its 1).
Now i want to use the mapping-function to replace "0" with "OK" and "1" with "Warning".
Is there any way to map them all in one rule or do i have to set up a rule for each?

**Comment by jdbranham** [comment]
Sure - you can use a regex in the value mapping 'alias' box. 
Try `/.*/` as the alias matcher.
