### ISSUE TITLE
Getting error "this.$http is not a function" error in Grafana v6.5.0

### ISSUE THREAD

**Issue by hairyhenderson** [jdbranham/grafana-diagram#144]
Until recently I've been able to use this plugin with Grafana, but now I'm starting to get an error `this.$http is not a function`.

There's nothing useful logged in the console that I can see.

The mermaid coming from the URL I'm hitting is correctly-formatted (and hasn't changed in months), though it doesn't seem like the plugin is even trying to reach the backend...

Is there an incompatibility with recent versions of Grafana?

**Comment by briangann** [comment]
There is a problem with v6.5.0 - to get this plugin to work again, you'll need to 6.5.2.

You may still run into CORS blocking in the browser also.

**Comment by hairyhenderson** [comment]
Thanks @briangann - I just realized that 6.5.2 was released. Will see if that helps!

**Comment by hairyhenderson** [comment]
Ok, confirmed that this works again with 6.5.2!
