### ISSUE TITLE
Prometheus and IPs

### ISSUE THREAD

**Issue by IPZAaron** [jdbranham/grafana-diagram#146]
Hello!

I've been playing around with this for my company's monitoring stack, though I'm having some issues with utilizing Prometheus and IPs as the instance names. I've tested with the example, using "localhost" and get a successful query with the "up" query, but when I try to swap out "localhost" with a target IP, change the port and job name, I can't get the specific item to change color like it did before.

I believe this issue is coming from the IPs having a period in them and I've added a period to the metric character replacement, though I got no success from that either.

Is it something I just glassed over in the docs?

Thank you!

**Comment by jdbranham** [comment]
Hi!
You might turn the legend on, to see the exact name of the metric alias.
Then in the diagram definition, use that alias.
I'll try to replicate this locally.

**Comment by IPZAaron** [comment]
Wow, so that's a life saver suggestion.

I have them in groups, too and I think those have to be in there.

Works just fine with the periods now. Thank you much!
