### ISSUE TITLE
The added metrics cannot be displayed perfectly

### ISSUE THREAD

**Issue by eryajf** [jdbranham/grafana-diagram#147]
I would like to add the average CPU usage of the corresponding host in this node, but now the effect is shown as follows:

![image](https://user-images.githubusercontent.com/33259379/78102342-b0108380-741c-11ea-96f1-3982ff63e7c2.png)

> If the image above is not viewable, you can see the renderings at the following URL
> https://s1.ax1x.com/2020/04/01/G16jxA.png

I tried to customize the height `style api height:80` by style, but it still didn't work:

![image](https://user-images.githubusercontent.com/33259379/78102172-3ed0d080-741c-11ea-931a-b7424c293c38.png)

>If the image above is not viewable, you can see the renderings at the following URL
>https://s1.ax1x.com/2020/04/01/G1c1G4.png

**Comment by jdbranham** [comment]
Hi - which version of the plugin are you using? Also, which browser?

**Comment by NobleVision** [comment]
Upgrading to 7.0 resolves this issue, but does not resolve the issue where values in the connecting lines is truncated.

**Comment by eryajf** [comment]
> Hi - which version of the plugin are you using? Also, which browser?

Then I found the reason, because I added the jump connection to the cluster and it was like this, and when I removed the jump connection, the phenomenon disappeared and the data showed normal.

**Comment by shrutiseth** [comment]
![image](https://user-images.githubusercontent.com/45349166/85947571-82eb4880-b919-11ea-880d-07ae727c6e4a.png)

Full text is not visible on the boxes. In the screenshot here I just added new panel, selected Diagram Visualization.
On the side pane, the Size and Legend section are not displayed properly. 

Grafana Version: 7.0.4
Diagram Plugin Version: 1.6.2
![image](https://user-images.githubusercontent.com/45349166/85947629-e9706680-b919-11ea-91d4-a614d66c004d.png)

**Comment by jdbranham** [comment]
Fixed in v1.6.3
https://github.com/jdbranham/grafana-diagram/commit/746825aca5c0a925fa8c2f8d4f9f08a1988aadac

 and in v1.7
