### ISSUE TITLE
Does not play well with grafana 6.6

### ISSUE THREAD

**Issue by yellowpattern** [jdbranham/grafana-diagram#148]
When using this plugin with grafana 6.6, there are some very unexpected occurances:
https://github.com/grafana/grafana/issues/23347

The web page layout no longer looks anything like what's on this page:
https://grafana.com/grafana/plugins/jdbranham-diagram-panel
 - see attachment.
![Screen Shot 2020-04-05 at 3 30 21 pm](https://user-images.githubusercontent.com/24280758/78467679-6395b280-7752-11ea-8734-a6c22a6c9f52.png)

**Comment by jdbranham** [comment]
#133

**Comment by jdbranham** [comment]
resolved by --

 https://github.com/jdbranham/grafana-diagram/pull/155/commits/882c80f10259b08f8c006353802a941d1ffdbe99
