### ISSUE TITLE
Using sequence diagram

### ISSUE THREAD

**Issue by mdkamijo** [jdbranham/grafana-diagram#149]
Hi!

I do really love this plugin and I want to use it more. This time I need to display a sequence diagram. No problems showing the sequence diagram in it self but connecting metrics... I can not find out how to do that. Is it so that the diagram plugin doesn't support sequence diagrams or does it? If it does, is there any documentation of how it works?

Here is an example looking like the simple test I have made:
Metrics aliases:
```
updateRequest
sendRequestData
pushRequestResult
requestResult
```

My marmaide sequence diagram looks like this (example):
```
sequenceDiagram
    participant app01
    participant app02
    participant app03
    app01 ->> app02: updateRequest
    app02 ->> app03: sendRequestData
    app03 ->> app02: pushRequestResult
    app02 ->> app01: requestResult
```

**Comment by jdbranham** [comment]
Thank you @mdkamijo 
I've just added style functions for sequence diagrams edge labels - 

![image](https://user-images.githubusercontent.com/2660839/79716096-393c0d00-829b-11ea-98fa-2e2e56be282f.png)

**Comment by jdbranham** [comment]
It's not real pretty. I should spend some time making everything a bit more beautiful...

**Comment by mdkamijo** [comment]
Wow... thanks!
