### ISSUE TITLE
It would be good to use together with postgres datasource

### ISSUE THREAD

**Issue by lachatak** [jdbranham/grafana-diagram#152]
Hi,
The plugin is amazing, however, unfortunately it cannot be used together with postgres datasource https://grafana.com/grafana/plugins/postgres.
Is there an easy way to deliver this capability?
thx

**Comment by jdbranham** [comment]
Thanks! I haven't tested with it yet. But I'll check it out.

**Comment by lachatak** [comment]
Is there any way to help you to speed this up. This plugin is very cool but we source every data from postgres and unfortunately cannot use the plugin. thx

**Comment by lachatak** [comment]
I have managed to test with postgres data source. It works perfectly fine. The `type` field returned from the query is exposed as `alias` so it can be used in a mermaid flow.
Maybe the documentation needs a bit of update then. I try to raise a PR for that.

**Comment by avandermeer** [comment]
@lachatak How did you get this working? I tried to add a custom column named `type` in my query, but it was not parsed as an alias.

**Comment by avandermeer** [comment]
> 
> 
> @lachatak How did you get this working? I tried to add a custom column named `type` in my query, but it was not parsed as an alias.

Never mind, I solved it. Apparently, the plugin expects time as the first value (so I just set it to 0). 

**Simple working example** (with grafana 8.0.4, grafana diagram 1.7.3):

```sql
select 
       0 as time,
       100 as alias1,
       200 as alias2

```

Mermaid config:
```mermaid
graph LR
      alias1 --> alias2
```
