### ISSUE TITLE
Make sequence diagram prettier

### ISSUE THREAD

**Issue by mdkamijo** [jdbranham/grafana-diagram#153]
@jdbranham wrote in #153 that the sequence diagram thing should be made prettier, I do agree :)

Is that something you are planing on doing?

Can the changes be done within the "Custom Styles" part in the visualisation part in Grafana or does it have to be done in code? If it's possible in "Custom Styles" do you have any documentation about how it works?

**Comment by jdbranham** [comment]
It's on the radar, just trying to find time! 
I'm looking for a couple sponsors of development, so I can spend more time on it - gotta pay the bills =\

The custom styles sections is essentially a CSS input. I typically use "Chrome Developer Tools" to select the diagram elements and test css rules.

Here's an example of how you might define some styles - 
```
.diagram rect, .diagram circle, .diagram ellipse, .diagram polygon {
    fill: #BDD5EA;
    stroke: red !important;
    stroke-width: 3px !important;
}
.diagram path {
    stroke: blue !important;
}
```
Or if you have multiple diagrams on the same dashboard, and want unique styles for each 
```
#diagram_2 .node rect, #diagram_2 .node circle, #diagram_2 .node ellipse, #diagram_2 .node polygon {
    fill: #BDD5EA;
    stroke: red;
    stroke-width: 3px;
}
#diagram_2 path {
    stroke: blue !important;
}
```

Let me know if that helps!
