### ISSUE TITLE
HTML in the graph

### ISSUE THREAD

**Issue by k-0** [jdbranham/grafana-diagram#158]
In version 1.6.1 I used this and it works fine:
`A[<font size='3.5px'><br><b>Grafana-Server<b><br><br>]  `
In version 1.6.2 it shows me the whole HTML` "<font size='3.5px'><br><b>Grafana-Server<b><br><br>"` instead of the formated string.

**Comment by patrickue** [comment]
Having the same issue. A very critical function to be rendered useless. Bug or feature?

**Comment by jdbranham** [comment]
Not sure what happened in v1.6.2, but it's working in 1.6.3. It's not available on Grafana.com yet, but I'll publish it soon.  

![image](https://user-images.githubusercontent.com/2660839/93690181-1d7fa180-fa9b-11ea-9a53-653548a66c76.png)
