### ISSUE TITLE
Add url 

### ISSUE THREAD

**Issue by keith6014** [jdbranham/grafana-diagram#160]
is it possible to add a URL for an item?

For example

foo --> bar

if I click on bar it goes to a URL

**Comment by jdbranham** [comment]
Yes, you can use the `interaction` functions -  

https://mermaid-js.github.io/mermaid/diagrams-and-syntax-and-examples/flowchart.html#interaction

Example using the `click` function - 
```
graph LR;
    A --> SAVANTLY;

click SAVANTLY "http://savantly.net" _blank
```
