### ISSUE TITLE
Support for value mapping to work

### ISSUE THREAD

**Issue by gjreiloba** [jdbranham/grafana-diagram#162]
Hi,

When i put a series alias in Value Mappings tab, there is no change on diagram.

![image](https://user-images.githubusercontent.com/69263939/89451880-3fafa100-d733-11ea-8ea8-adffe8d251a1.png)

My mermaid code:
graph LR

C2470[(C2470)] == "#CF572p14" === CF572[(CF572)]
C2470[(C2470)] == "#CF531p14" === CF531[(CF531)]
CF572[(CF572)] == "#CF572p15" === CF571[(CF571)]
CF531[(CF531)] == "#CF530p15" === CF530[(CF530)]
CF571[(CF571)] == "#CF571p15" === CF570[(CF570)]
CF530[(CF530)] == "#CF529p15" === CF529[(CF529)]
CF570[(CF570)] == "#CF570p15" === CF569[(CF569)]
CF529[(CF529)] == "#CF528p15" === CF528[(CF528)]
CF569[(CF569)] == "#CF569p15" === CF568[(CF568)]
CF528[(CF528)] == "#CF566p15" === CF566[(CF566)]
CF568[(CF568)] == "#CF568p15" === CF567[(CF567)]
CF566[(CF566)] == "#CF567p15" === CF567[(CF567)]

My value is "1", but i cant get the UP string

![image](https://user-images.githubusercontent.com/69263939/89452170-9d43ed80-d733-11ea-8131-52e53ffb8ec0.png)

What i'm doing wrong?

Thanks!!

**Comment by jdbranham** [comment]
Hi! 
The hash `#` is a special marker for the metric name, which means to show the raw numeric value.
If you remove the # it should display the value map text correctly.   

Here's a test using your diagram definition - [using v1.6.2]. 

![image](https://user-images.githubusercontent.com/2660839/93687890-2a929580-fa87-11ea-9b28-bb32bf26d576.png)

The value mapping. 
![image](https://user-images.githubusercontent.com/2660839/93687883-177fc580-fa87-11ea-9c74-f84b680a38f5.png)


Or using the `@` prefix instead -  
![image](https://user-images.githubusercontent.com/2660839/93687970-e94eb580-fa87-11ea-8d22-c8b3532ba5a7.png)

Unfortunately the color marker is not shown when using that syntax.  
v1.7 of the plugin has better support for field level formatting, but requires Grafana v7.x. 

I also, noticed the  width/height of the link boxes is not great - I should have a patch for that soon.
