### ISSUE TITLE
Null value change to 0

### ISSUE THREAD

**Issue by BlackMoon2020** [jdbranham/grafana-diagram#164]
Hi,

I am trying to use the plugin to monitor application running on same server using the diagram to.group them by category.
Backend query is on influxdb, count(cpu) based on certain pattern and time frame.
If i got 3 process running, if i stop one process, can be flag as Warning status with threshold, value mapping, work.like a charm.
Same with 2 process down.

Problem is with 3 process down as query return null, not possible to flag CRITICAL.

1.
Either is there way to override null to 0.
So can use value mapping.

2.
Is it possible to set default value of the box to red color, using dark theme, default is blue.
At least, if can show Red color background to flag all process for that group are down and best with wording Critical.

Thank you in advance for your help.

Cheers,
Martial

**Comment by jdbranham** [comment]
Both of these methods can be used in v1.7 that was checked in last night =]  

It's not published on Grafana.com yet, but you may try it by either installing the plugin manually. 
Unzip into your plugins folder - https://github.com/jdbranham/grafana-diagram/archive/master.zip

Or checking this repo out, and running `docker-compose up` from your terminal [assuming you have 'docker-compose' installed]

**Comment by jdbranham** [comment]
Your thought about a default color can work like this - 

Use a custom style that selects the label node by the 'composite ID', in this case `D-series`, and give it a default fill -  
![image](https://user-images.githubusercontent.com/2660839/93689591-b3b0c900-fa95-11ea-92fe-188cb844a111.png)

No data points are returned from the series, so node takes default color  -  
![image](https://user-images.githubusercontent.com/2660839/93689571-79472c00-fa95-11ea-8bb5-b2252494d2ff.png)

Or if you want all the nodes to have a default color, you can use a style like - 
```
#diagram_2 rect.label-container {
  fill: red;
}
```

In `#diagram_x` , the `x` is the panel ID. This may change if you delete and re-add the panel.

**Comment by BlackMoon2020** [comment]
Thank you for prompt reply, it work with Css custom CSS mention above, now nicely integrated with grafana 7.x

Fyi a typo #diagram_x does not work. 
But #diagram-x worked to apply default color to same shape.

I change diagram to have subgraph representing a server basically matching a query. I got one problem, moving label to the top of subgraph, not middle.

#servername .label{font-size:15px} this work fine, but cannot find how to put it to the top of subgraph, your help.will be appreciated

**Comment by jdbranham** [comment]
Good catch - I updated the comment.

For the subgraph, we should adjust the way the label is replaced to ignore subgraph. 
Until that is done, you might patch it with a css style like this, adjusting the 'top' parameter as necessary -  
```
foreignObject {
  overflow: visible;
}

#A-series  .diagram-value {
  position: relative;
  top: -75px;
}
```


![image](https://user-images.githubusercontent.com/2660839/93921458-345e0800-fcd6-11ea-9826-c1e75f3bc9fe.png)

**Comment by BlackMoon2020** [comment]
Thank you for prompt reply, I also found a solution as per below

#<series> .label {
font-size: 20px;
Text-transform: uppercase;
Text-align:center;
Transform: translate3d(-150px, -120px, 10px)
}

Last line to move either x or y.

Else you can also use y only or x only. Not both together
If need both x and y, need to used 3d one
Transform: translateY(-140px)
