### ISSUE TITLE
Feature: Drill-down links

### ISSUE THREAD

**Issue by RichiH** [jdbranham/grafana-diagram#17]
Grafana proper supports drill-down links from the panel title. It would be very useful to be able to click on/next to a node/edge and get to a different dashboard.

**Comment by blysik** [comment]
+1

**Comment by Drabert** [comment]
+2 -- or if the nodes were some how collapsible

https://www.youtube.com/watch?v=XXy7hNVhq9k

**Comment by SuperKy3mu4** [comment]
It will be very useful features. At least links to different dashboard

**Comment by waqark3389** [comment]
+1 @jdbranham When can we expect 1.5 :)

**Comment by gomlgs** [comment]
https://github.com/jdbranham/grafana-diagram/pull/46 should make some of this easier, when combined with https://knsv.github.io/mermaid/#interaction23.

**Comment by jdbranham** [comment]
This works now, but I don't remember in which version, so I cant link here =\

**Comment by jdbranham** [comment]
Checking old issues....
Does this work as expected now?
