### ISSUE TITLE
Issues after Upgrade to 7.x

### ISSUE THREAD

**Issue by boernd** [jdbranham/grafana-diagram#177]
Hi,

after upgrading to Grafana 7.x the panels are broken. I get the following error:

```
Error rendering diagram. Check the diagram definition

TypeError: Cannot read property 'map' of undefined
```

Is there something to migrate or has the diagram to be redone in the new version?

**Comment by jdbranham** [comment]
Good question - 
The option structure is much different in 7x. 
Could you share the panel json for one that's failing (omit anything sensitive)?

**Comment by transacid** [comment]
I have attached an example panel.json 
[flowchart-panel.json.txt](https://github.com/jdbranham/grafana-diagram/files/5546036/flowchart-panel.json.txt)

**Comment by phule888** [comment]
I have the same problem as the OP.  No idea if the option structure was added/modified, but I receive the identical message/error.  Any suggestions/recommendations ?

Attached here is the panel.json (which fails)
[panel json.txt.txt](https://github.com/jdbranham/grafana-diagram/files/5710767/panel.json.txt.txt)

**Comment by ahgit101** [comment]
Hi,
Any updates on this. Just upgraded to version 1.7.1
And even simple:
**graph LR
A --> B**

Gives error:
**Error rendering diagram. Check the diagram definition
TypeError: Cannot read property 'map' of undefined**

Using Grafana version v7.0.5

Many thanks

**Comment by jdbranham** [comment]
https://github.com/grafana/grafana-plugin-repository/pull/924
