### ISSUE TITLE
API support is dropped?

### ISSUE THREAD

**Issue by TomL-dev** [jdbranham/grafana-diagram#178]
After migrating to grafna 7.x with 1.7.1 of the plugin, it looks like you can't fill in the api anymore.

![image](https://user-images.githubusercontent.com/26207844/99969971-791c2300-2d9b-11eb-8919-3f6fb7a11e71.png)

I tried pasting in the URL in the textbox, but it then complains it's not valid:

```
Error: Parse error on line 2: ...al,sans-serif"}}}%%https://dev.api.cyph ----------------------^ Expecting 'open_directive', 'NEWLINE', 'SPACE', 'GRAPH', got 'ALPHA'
```

I checked if the api response i got was valid, but doing a manual call and pasting in the mermaid syntax gave me a valid diagram.

Can you please take a look at this?

**Comment by psangwan** [comment]
I have the same issue, after the upgrade, the working diagram plugin stopped working and there is no URL reference now.

I see it is mentioned in the roadmap, but that means the URL reference which was previously working is not working anymore and it is put roadmap.

please provide some details.

**Comment by TomL-dev** [comment]
@jdbranham can you please update on this?

**Comment by jdbranham** [comment]
Added basic remote diagram definition functionality - 
https://github.com/jdbranham/grafana-diagram/commit/389bd8f9ffa7cd16d91b730f20eb3f4dd2876da5


![image](https://user-images.githubusercontent.com/2660839/108604589-7c13b900-7374-11eb-94d4-72ce71291600.png)


using this example - https://gist.github.com/jdbranham/7e9d437efd252d5b6d04e04fd4e3d524#file-example-diagram-txt
