### ISSUE TITLE
Example graph does not work with database

### ISSUE THREAD

**Issue by yellowpattern** [jdbranham/grafana-diagram#180]
I tried tried the example with [(database)] from the home page but it did not work with 1.6.3.

![Screen Shot 2020-12-20 at 3 24 06 am](https://user-images.githubusercontent.com/24280758/102694106-08b9d200-4273-11eb-88ce-c1b4c35331a0.png)

**Comment by jdbranham** [comment]
This should work in 1.7+ 

![image](https://user-images.githubusercontent.com/2660839/120823442-0e535d80-c51d-11eb-89db-92459b641f5e.png)
