### ISSUE TITLE
Diagram plugin breaks with grafana 7.3.x upgrade

### ISSUE THREAD

**Issue by ShilpaSivanesan** [jdbranham/grafana-diagram#181]
Diagram Plugin  versions (1.7.1 and 1.6.4) breaks with **error: property map not found** with grafana 7.3.x versions

**Comment by jgarciadelanoceda** [comment]
Same happens to us.
If we install via grafana-cli it installs 1.6.2 version and we have more than one mermaid in a Dashboard and mermaids are mixed.

![image](https://user-images.githubusercontent.com/6615999/106253661-0f474c00-6218-11eb-9878-364d0265163f.png)

We upload Grafana from 4.6.2 version to 7.3.7. In version 4.6.2 mermaid are not being mixed

**Comment by mjiderhamn** [comment]
Duplicate of #177

**Comment by jdbranham** [comment]
closing for duplicate
