### ISSUE TITLE
An unexpected error happened while trying disable anonymous reporting in plugin Help section

### ISSUE THREAD

**Issue by gm7y8** [jdbranham/grafana-diagram#192]
<img width="633" alt="Screen Shot 2021-03-29 at 3 10 27 PM" src="https://user-images.githubusercontent.com/12487613/112906552-33e96400-90a1-11eb-8105-4b1d4c33fc2f.png">

**Comment by jdbranham** [comment]
anonymous reporting removed in v1.7.1

**Comment by jdbranham** [comment]
https://github.com/jdbranham/grafana-diagram/releases/tag/v1.7.2

**Comment by gm7y8** [comment]
@jdbranham  thanks
