### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by RichiH** [jdbranham/grafana-diagram#20]
Sorry for abusing issues, but I don't know of any other way to contact you... :/

Will there be a new release soon so I can use 7b2105d6b132795c8fb8279eab54e7d6da30d417 ?

Alternatively, is there a way to use your plugin from source? It's the first external plugin I have any interest in, so I don't know how to do this...

**Comment by coussej** [comment]
Normally, you can simply clone the github repo in `/var/lib/grafana/plugins` and restart grafana.

**Comment by jdbranham** [comment]
requested v1.3.1 to be promoted to Grafana.net
https://github.com/grafana/grafana-plugin-repository/pull/59
