### ISSUE TITLE
Unsigned Plugin Warning

### ISSUE THREAD

**Issue by ahegel** [jdbranham/grafana-diagram#208]
I'm trying to install this plugin on my Grafana instance, but it is saying it is not signed:

<img width="1061" alt="Screen Shot 2021-06-23 at 9 25 31 PM" src="https://user-images.githubusercontent.com/5776417/123202491-90260f00-d469-11eb-95de-26bc78aa38f8.png">

I installed it from within the grafana container with:
```
grafana-cli plugins install jdbranham-diagram-panel

```

Are there any plans for having this plugin signed?

**Comment by jdbranham** [comment]
Looks like we're still waiting for the latest version to be released -  
https://github.com/grafana/grafana-plugin-repository/pull/964

If you want to install it now, you can download the zip file and decompress it in your Grafana plugins folder - 
https://github.com/jdbranham/grafana-diagram/releases/tag/v1.7.3

**Comment by jdbranham** [comment]
You might also be able to do it from the CLI -  
https://grafana.com/docs/grafana/latest/administration/cli/#override-default-plugin-zip-url

Using a command like this -  
`grafana-cli --pluginUrl https://github.com/jdbranham/grafana-diagram/releases/download/v1.7.3/jdbranham-diagram-panel-1.7.3.zip plugins install jdbranham-diagram-panel`

**Comment by briangann** [comment]
v1.7.3 was just published, sorry for the delay!

**Comment by jdbranham** [comment]
Awesome. Thanks Brian!
