### ISSUE TITLE
No value boxes on diagram

### ISSUE THREAD

**Issue by avandrel** [jdbranham/grafana-diagram#22]
Hi! I'm testing this plugin with ElasticSearch datasource (I don't really know if it's officially supported) and everything but one thing works fine. That one thing are missing value boxes on diagram. As you could see below, I have some values in series, they are also generating proper gradients.
Am I missing something in setting? I was playing with it for couple of minutes but without success.

![missing_value_plates](https://cloud.githubusercontent.com/assets/3316117/19647302/bb56bd9c-99fd-11e6-91e8-ed1b11957994.png)

Edit: It has some connection to styles and used browser. I can see in firebug (in FireFox), that there are some hidden html nodes with proper values. I switched to Chrome and value boxes are visible.

**Comment by kfox1111** [comment]
I've seen this in firefox too. Switching to chrome, the missing box shows up.

**Comment by jdbranham** [comment]
Adding fix to next release.

**Comment by cosullivan86** [comment]
Hi All,
I'm having the same problem, I had it working for most of the day and then all of a sudden it stopped working, I've tried both chrome and firefox to ensure it wasn't a browser issue to no avail. I also deleted and recreated the entire dashboard (thank god for copy and paste), and again it didn't work, I have noticed however that I get WARN logs in grafana now with the following:

2017/06/17 23:09:13 http2: server: error reading preface from client 10.228.5.60:63221: timeout waiting for client preface

restart of services hasn't helped either :'(

any one resolved this yet?

by the way, this is a great panel!!! (when i get it working again)
