### ISSUE TITLE
Circles aren't filled

### ISSUE THREAD

**Issue by martbhell** [jdbranham/grafana-diagram#23]
With grafana-digram version 1.3.0 and latest on git the circles are filled when I am making the diagram, but not after  reloading the page/dashboard in grafana.

Tested with grafana 3.1.0 and 3.1.1. Chrome and Firefox.

I view this page:

<pre>https://URL/grafana/dashboard/db/diagram-test-panel-2?panelId=3&fullscreen&edit&editorTab=Diagram</pre>

or this:

<pre>
https://URL/grafana/dashboard/db/diagram-test-panel-2?editorTab=General&panelId=3&fullscreen&edit
</pre>

The circles are filled.

But if I view: <pre>https://URL/grafana/dashboard/db/diagram-test-panel-2</pre>

They are not.

**Comment by RichiH** [comment]
Screenshots would be helpful

**Comment by martbhell** [comment]
I'll get back with those next week.

**Comment by martbhell** [comment]
http://imgur.com/a/QQzKe

**Comment by jdbranham** [comment]
@martbhell 
Are there any errors in the browser console when this happens?

**Comment by martbhell** [comment]
Sure! 

When they are not filled: http://pastebin.com/m3HhZ6Xb
When they are filled: http://pastebin.com/RzhnkAqt

Where they are filled I see "updating svg style" early in the console output rather than at the end.

**Comment by martbhell** [comment]
Same issue with version 1.4.0 of the plugin
