### ISSUE TITLE
Bug? Link as a custom HTML is not working anymore after it adds a Value...

### ISSUE THREAD

**Issue by atec111** [jdbranham/grafana-diagram#249]
Definition of the particular Relation:

`ProductA("ProductA <a href='https://google.com'>🔗</a>") -.-> ProductB{{"👑 ProductB"}}`

The Link Symbol is clickable as long as no Value is shown from a query. (My query has only Values if this Product has an active Grafana Alert for this Product)
When there is a Value (e.g. 1) it is shown below the Text, coloring with threshold is working, but the Link is not clickable anymore!

If I inspect the html of this, the hyperlink has been removed and `<br>[Value]` has been added.
Like: `ProductA("ProductA 🔗<br>1") -.-> ProductB{{"👑 ProductB"}}`

Am I doing something wrong? Known Issue?

 
PS: Grafana v9.5.5 (284c43c23d)

**Comment by jdbranham** [comment]
@atec111 

Instead of embedding the link text, you add a `click` handler like this - 
```
graph LR
      A-series--> B-series

click B-series "https://savantly.net/"
```

Does that help?
![image](https://github.com/jdbranham/grafana-diagram/assets/2660839/a3d807a8-e132-4be4-ba14-3fe75cd81394)
