### ISSUE TITLE
graphviz support

### ISSUE THREAD

**Issue by LrWm3** [jdbranham/grafana-diagram#251]
The org I worked for has added basic graphviz support to this plugin.  The reason being thats what gstreamer produces when generating a diagram of the pipeline structure.

Most of the features of this plugin don't work at the moment but we can render a graphviz diagram, and we added zoom and pan as it can be hard to see otherwise.

Would it make more sense to try and publish it as a separate plugin or do you think it would be worth attempting to roll into this plugin and let users decide if they want to render using mermaid or graphviz.

Thanks.

**Comment by jdbranham** [comment]
That sounds interesting @LrWm3 !
graphviz support could be useful in other cases 🤔   

If it's developed in a way that lets the user pick which diagram syntax is used, then it might work.  And/or there's overlap in how things are styled....

**Comment by LrWm3** [comment]
We will see how it goes on our end and see if we can get things working for it.

If it looks good, we will open a PR where people can select either mermaid or graphviz.

**Comment by madansu** [comment]
@LrWm3 any update on this ?

**Comment by LrWm3** [comment]
We got it working for our purposes but I don't think it would be sufficiently compatible with the existing plugin without more work.
