### ISSUE TITLE
Is this plugin ready for Grafana to remove Angular support?

### ISSUE THREAD

**Issue by Bernardozomer** [jdbranham/grafana-diagram#256]
As per [this link](https://grafana.com/docs/grafana/latest/developers/angular_deprecation/), Grafana has already deprecated Angular and will completely remove support to it by Grafana 11, which should release later this year.

I know you have used Angular in the past. Is that still the case? I see it mentioned in [.config/webpack/webpack.config.ts](https://github.com/jdbranham/grafana-diagram/blob/2f1fdb69fff1dd889bf1f7e183850f07c842f989/.config/webpack/webpack.config.ts#L55), but nowhere else. Have you migrated already? Will this plugin work once Grafana 11 rolls out?

Cheers.

**Comment by xaner4** [comment]
Hi @Bernardozomer,
I have been check this one out and the file you are referring to is automatically created by Grafana them self when running the command 
```bash
$ npx @grafana/create-plugin@latest
```
or
```$
$ npx @grafana/create-plugin@latest update
```

So i think that that part is just to ignore and will probably not be affected from Grafana 11 dropping Angular support

**Comment by Bernardozomer** [comment]
Thank you @xaner4 . If anyone has other insight, I'd love to hear it.

**Comment by Bernardozomer** [comment]
Just realized the latest release on GitHub is v1.10.0, while in Grafana it is 1.7.3. There is even a link from the plugin page to a document explaining AngularJS will be deprecated.

![image](https://github.com/jdbranham/grafana-diagram/assets/33356553/0d7391bf-8708-410a-8b2b-b038051c9892)

**Comment by Bernardozomer** [comment]
Thank you, @jdbranham ! I believe we can close this issue since this doesn't appear to use Angular.

**Comment by Bernardozomer** [comment]
By the way, @jdbranham , did Grafana give you any ETA for approving the new version for the marketplace?

**Comment by briangann** [comment]
I checked the review queue and it looks like some changes were requested and may not have been seen.

@jdbranham  I'll be on plugin review rotation next week also and would be happy to assist pushing it through the review process.

**Comment by xaner4** [comment]
Is there any progress to get this out on Grafana @jdbranham @briangann?
Anything that i can help with to get this published?
