### ISSUE TITLE
Connecting subgraphs

### ISSUE THREAD

**Issue by Bifrozt** [jdbranham/grafana-diagram#27]
I can't figure out if its possible to connect subgroups or not, if so, would it be possible to assign a time series value to the subgroup?

**Comment by jdbranham** [comment]
Hi @Bifrozt 
I'm not sure. Could you draw a pic of what it might look like, and attach it here?

**Comment by Bifrozt** [comment]
Hi @jdbranham,

Sorry for my vague question here and the tittle should say **Connecting subgraphs** not subgroups.

I'm collecting metrics from a network that's divided into multiple zones.
Each zone is basically identical and the same metrics is collected from each zone.
Some of these metrics will quickly tell me if there's an issue on one of the nodes within a given zone

I tried creating subgraphs for each zone and add each node in the zone to that subgroup.
This works fine for some scenarios but, for my use-case, i don't really care if one or a small number of nodes are sending metrics that indicates an issue (the rest of the zone is still operational).

Initially i had two questions
1. How to connect one subgraph to another in the same manner as one would connect one diagram object to another
2. How to assign a metric value to a subgraph

I've figured out how to solve **2.**, i didn't notice the mertic value next to the subgraph name (i.e _Zone1 1.5_)
![subgraphs](https://cloud.githubusercontent.com/assets/8437560/20445251/9cf7027c-add4-11e6-8ee1-490d8cd90862.png)
Now im trying to find a way to set thresholds for a subgraph, this would make it easier to know when a zone is having issues.

As for **1.**. I'd like to keep the layout as shown in the previous picture, nodes within a subgraph but, be able to connect the subgraphs as one would connect other elements - is this possible?
![subgraphs_2](https://cloud.githubusercontent.com/assets/8437560/20445662/3942e672-add6-11e6-86fe-ead7c40bd2f1.png)

Anyways, i apologize for the confusing ticket tittle and i absolutely love this plugin - awesome work! :smile:

**Comment by jdbranham** [comment]
Thank you @Bifrozt !!
I'm looking into this.

**Comment by jdbranham** [comment]
Unfortunately there is not currently a way to do this -
https://github.com/knsv/mermaid/issues/197

**Comment by Bifrozt** [comment]
> Unfortunately there is not currently a way to do this

I put my faith in the "not currently" will change soon :smile: 
Thanks for looking into this and keep up the good work!
