### ISSUE TITLE
Zoom/Size option

### ISSUE THREAD

**Issue by cosmos1978** [jdbranham/grafana-diagram#29]
Thanks for this great plugin. I have it on a bunch of big screens to display some realtime diagrams of our server park.

But on a big TV the diagrams are to small to read.

It would be great if there was a size settings in percentage.

Thanks

**Comment by jdbranham** [comment]
Thanks @cosmos1978 !
It shouldn't be too hard to add that. I'll put it in the next release.

Any chance you could send a pic of your setup? I want to show my girlfriend I'm not wasting my time! 
=)

**Comment by RichiH** [comment]
FOSDEM will use it and I will refer to it in two talks in front of hundreds
of people next week.

Richard

Sent by mobile; excuse my brevity.

**Comment by cosmos1978** [comment]
still work in progress. many more nodes to add and I also want to include
data to the arrows themselfs to show network bandwidth.



2016-11-18 3:53 GMT+01:00 Jeremy <notifications@github.com>:

**Comment by jdbranham** [comment]
@cosmos1978 
Are you using the 'scale' option on the display tab?

**Comment by cosmos1978** [comment]
What do you mean whith the scale option.

I see no such thing under the display tab ?

**Comment by jdbranham** [comment]
Ah yes, it's available in the the latest version, which has not been made available in Grafana.org yet.
https://github.com/grafana/grafana-plugin-repository/pull/66 

// Adding @daniellee 

These are the newest Display Options

![image](https://cloud.githubusercontent.com/assets/2660839/20678546/bf13fcf4-b55c-11e6-996e-b80a6956ecaf.png)

**Comment by cosmos1978** [comment]
when will it be pushed to grafana.net ?

**Comment by daniellee** [comment]
Forgot to mention here that this update was published on grafana.net a week ago. cc @cosmos1978

**Comment by RichiH** [comment]
https://dashboard.fosdem.org/dashboard/db/ulb-switching-overview

**Comment by RichiH** [comment]
As per https://github.com/FOSDEM/video/issues/43, this was used at FOSDEM last weekend.
