### ISSUE TITLE
Diagram not wrapped in viewport

### ISSUE THREAD

**Issue by Atoms** [jdbranham/grafana-diagram#3]
we have 3 master servers and 13 slave servers, all 3 master servers go to all 13 servers, when i add such graph i cannot see all hosts in viewport
![grafana testing](https://cloud.githubusercontent.com/assets/9615/19118769/23533ad8-8b26-11e6-9544-093f606d42cd.png)
There is somwhere 3rd master server...

**Comment by jdbranham** [comment]
You might try changing the orientation of the graph in the definition.

TD becomes LR

**Comment by Atoms** [comment]
Thats does not help, then we cannot see anything written on boxes :(

![grafana testing1](https://cloud.githubusercontent.com/assets/9615/19119573/e448d552-8b28-11e6-9289-5394dcbdd03a.png)

**Comment by jdbranham** [comment]
I modified the css to allow scrolling. It looks good locally.
Let me know how that works for you.

**Comment by jdbranham** [comment]
Smaller panels will scroll, and the bars disappear on larger panels -

![full](https://cloud.githubusercontent.com/assets/2660839/19123852/1d2ac020-8af6-11e6-81ec-b822baf4a4d0.PNG)
![scroll1](https://cloud.githubusercontent.com/assets/2660839/19123851/1d27526e-8af6-11e6-8a47-2c3dbe1b7f61.PNG)
![scroll2](https://cloud.githubusercontent.com/assets/2660839/19123853/1d3296c4-8af6-11e6-8119-0a1de212f391.PNG)

**Comment by Atoms** [comment]
how long before version appears as updatable in grafana ? :)

**Comment by jdbranham** [comment]
I should have a PR created sometime today =]

**Comment by jdbranham** [comment]
I created a PR. It should be available soon.

**Comment by jdbranham** [comment]
https://github.com/grafana/grafana-plugin-repository/pull/47

**Comment by DanCech** [comment]
It's live on grafana.net now :+1:

**Comment by jdbranham** [comment]
@DanCech 
I see it was merged, but there was a bug in my plugin.json [forgot a comma!!] so created a new PR with an updated commit #
Sorry!

**Comment by Atoms** [comment]
seems better but still it would be nice if is somehow tried to do better handling of diagram, cause if i have TV for monitoring, i would like to put this graph on, and you cannot scroll on tv :/ i don't know if mermaid can handle something like multiple levels of rows if count of hosts is greater than x..

**Comment by jdbranham** [comment]
mermaid doesn't, and I think the only way to fit more on the screen would be to use a higher resolution.
Maybe with this many nodes on one level, it would be better to use a heatmap.
