### ISSUE TITLE
Scaling & zoom

### ISSUE THREAD

**Issue by RichiH** [jdbranham/grafana-diagram#30]
Our, still very basic, rump diagram looks like so:
https://gist.github.com/markvdb/24d58acf8cba0a856bccfb1e174f99f9

http://knsv.github.io/mermaid/live_editor/#/view/Z3JhcGggVEQKCiAgc3ViZ3JhcGggdmlkZW8gYm94ZXMKICAgIHN1YmdyYXBoIGF3MTEyMAogICAgICBhdzExMjBjYW1bYXcxMTIwY2FtPGJyIC8-aXA6IDEwMC4xMDAuMTAwLjEwMDxiciAvPm11bHRpY2FzdDogMjI3LjAuMC4xXQogICAgICBhdzExMjBzbGlkZXNbYXcxMTIwc2xpZGVzPGJyIC8-aXA6IDEwMC4xMDAuMTAwLjEwMDxiciAvPm11bHRpY2FzdDogMjI3LjAuMC4xXQogICAgZW5kCiAgICBzdWJncmFwaCBhdzExMjEKICAgICAgYXcxMTIxY2FtW2F3MTEyMWNhbTxiciAvPmlwOiAxMDAuMTAwLjEwMC4xMDA8YnIgLz5tdWx0aWNhc3Q6IDIyNy4wLjAuMV0KICAgICAgYXcxMTIxc2xpZGVzW2F3MTEyMXNsaWRlczxiciAvPmlwOiAxMDAuMTAwLjEwMC4xMDA8YnIgLz5tdWx0aWNhc3Q6IDIyNy4wLjAuMV0KICAgIGVuZAogICAgc3ViZ3JhcGggYXcxMTI0CiAgICAgIGF3MTEyNGNhbVthdzExMjRjYW08YnIgLz5pcDogMTAwLjEwMC4xMDAuMTAwPGJyIC8-bXVsdGljYXN0OiAyMjcuMC4wLjFdCiAgICAgIGF3MTEyNHNsaWRlc1thdzExMjRzbGlkZXM8YnIgLz5pcDogMTAwLjEwMC4xMDAuMTAwPGJyIC8-bXVsdGljYXN0OiAyMjcuMC4wLjFdCiAgICBlbmQKICAgIHN1YmdyYXBoIGF3MTEyNQogICAgICBhdzExMjVjYW1bYXcxMTI1Y2FtPGJyIC8-aXA6IDEwMC4xMDAuMTAwLjEwMDxiciAvPm11bHRpY2FzdDogMjI3LjAuMC4xXQogICAgICBhdzExMjVzbGlkZXNbYXcxMTI1c2xpZGVzPGJyIC8-aXA6IDEwMC4xMDAuMTAwLjEwMDxiciAvPm11bHRpY2FzdDogMjI3LjAuMC4xXQogICAgZW5kCiAgZW5kCgogIHN1YmdyYXBoIHZvY3RvIGNvbnRhaW5lcnMKICAgIHN1YmdyYXBoIHZvY3RvaG9zdDAKICAgIHZvY3RvY29udGFpbmVyX2F3MTEyMAogICAgdm9jdG9jb250YWluZXJfYXcxMTIxCiAgICB2b2N0b2NvbnRhaW5lcl9hdzExMjQKICAgIHZvY3RvY29udGFpbmVyX2F3MTEyNQogICAgZW5kCiAgZW5kCgogIHN1YmdyYXBoIHN0cmVhbWluZyBiYWNrZW5kcwogICAgc3RyZWFtaW5nX2JhY2tlbmQxCiAgZW5kCgogIHN1YmdyYXBoIHN0cmVhbWluZyBmcm9udGVuZHMKICAgIHN0cmVhbWluZ19mcm9udGVuZDEKICBlbmQKCiUlIExpbmtzIGJldHdlZW4gZWxlbWVudHMKCiUlYXcxMTIwCmF3MTEyMGNhbSAtLT4gdm9jdG9jb250YWluZXJfYXcxMTIwCmF3MTEyMHNsaWRlcyAtLT4gdm9jdG9jb250YWluZXJfYXcxMTIwCnZvY3RvY29udGFpbmVyX2F3MTEyMCAtLT4gc3RyZWFtaW5nX2JhY2tlbmQxCgolJWF3MTEyMQphdzExMjFjYW0gLS0-IHZvY3RvY29udGFpbmVyX2F3MTEyMQphdzExMjFzbGlkZXMgLS0-IHZvY3RvY29udGFpbmVyX2F3MTEyMQp2b2N0b2NvbnRhaW5lcl9hdzExMjEgLS0-IHN0cmVhbWluZ19iYWNrZW5kMQoKJSVhdzExMjQKYXcxMTI0Y2FtIC0tPiB2b2N0b2NvbnRhaW5lcl9hdzExMjQKYXcxMTI0c2xpZGVzIC0tPiB2b2N0b2NvbnRhaW5lcl9hdzExMjQKdm9jdG9jb250YWluZXJfYXcxMTI0IC0tPiBzdHJlYW1pbmdfYmFja2VuZDEKCiUlYXcxMTI1CmF3MTEyNWNhbSAtLT4gdm9jdG9jb250YWluZXJfYXcxMTI1CmF3MTEyNXNsaWRlcyAtLT4gdm9jdG9jb250YWluZXJfYXcxMTI1CnZvY3RvY29udGFpbmVyX2F3MTEyNSAtLT4gc3RyZWFtaW5nX2JhY2tlbmQxCgoKc3RyZWFtaW5nX2JhY2tlbmQxIC0tPnN0cmVhbWluZ19mcm9udGVuZDE

It will include 24 video boxes over time which might introduce scaling issues. This is partially a "here, show this to your girlfriend" and partially a "is there anything you can do to make this fit nicely into one dashboard".

Also tagging @markvdb so he sees this.

**Comment by jdbranham** [comment]
Thanks @RichiH 

Does the Diagram resize to a better scale if you change the size of the window?
Also, is the 'scale' option selected on the display tab?

**Comment by mzsanford** [comment]
I also have a very wide diagram (You can find a [sanitized version here](https://mermaidjs.github.io/mermaid-live-editor/#/view/Z3JhcGggTFIKYmFja2xvZ0lucHV0PlN0YXJ0IFF1ZXVlXSAtLT4gc3BsaXR0ZXJbU3BsaXR0ZXJdCnNwbGl0dGVyIC0tPiBiYWNrbG9nUHJvY2Vzc0E-UHJvY2VzcyBBIFF1ZXVlXQpzcGxpdHRlciAtLT4gYmFja2xvZ1Byb2Nlc3NCPlByb2Nlc3MgQiBRdWV1ZV0Kc3BsaXR0ZXIgLS0-IGJhY2tsb2dQcm9jZXNzQz5Qcm9jZXNzIEMgUXVldWVdCmJhY2tsb2dQcm9jZXNzQSAtLT4gUHJvY2Vzc0FbUHJvY2VzcyBBXQpQcm9jZXNzQSAtLT4gYmFja2xvZ1Byb2Nlc3NBUmVzdWx0PlJlc3VsdCBRdWV1ZV0KYmFja2xvZ1Byb2Nlc3NCIC0tPiBQcm9jZXNzQltQcm9jZXNzIEJdClByb2Nlc3NCIC0tPiBiYWNrbG9nUHJvY2Vzc0JSZXN1bHQ-UmVzdWx0IFF1ZXVlXQpiYWNrbG9nUHJvY2Vzc0MgLS0-IFByb2Nlc3NDW1Byb2Nlc3MgQ10KUHJvY2Vzc0MgLS0-IGJhY2tsb2dSZWZvcm1hdHRlcj5SZWZvcm1hdHRlciBRdWV1ZV0KYmFja2xvZ1JlZm9ybWF0dGVyIC0tPiByZWZvcm1hdHRlcltSZWZvcm1hdHRlcl0KcmVmb3JtYXR0ZXIgLS0-IGJhY2tsb2dDUmVzdWx0PlJlc3VsdCBRdWV1ZV0KcmVmb3JtYXR0ZXIgLS0-IGJhY2tsb2dQcm9jZXNzRD5Qcm9jZXNzIEQgUXVldWVdCmJhY2tsb2dQcm9jZXNzRCAtLT4gUHJvY2Vzc0RbUHJvY2VzcyBEXQpQcm9jZXNzRCAtLT4gYmFja2xvZ1Byb2Nlc3NEUmVzdWx0PlJlc3VsdCBRdWV1ZV0KYmFja2xvZ1Byb2Nlc3NBUmVzdWx0IC0tPiBwcm9jZXNzQUhhbmRsZXJbSGFuZGxlcl0KYmFja2xvZ1Byb2Nlc3NCUmVzdWx0IC0tPiBwcm9jZXNzQkhhbmRsZXJbSGFuZGxlcl0KYmFja2xvZ0NSZXN1bHQgLS0-IHByb2Nlc3NDSGFuZGxlcltIYW5kbGVyXQpiYWNrbG9nUHJvY2Vzc0RSZXN1bHQgLS0-IHByb2Nlc3NESGFuZGxlcltIYW5kbGVyXQpzdWJncmFwaCBSZXN1bHQgRGFlbW9ucwpwcm9jZXNzQUhhbmRsZXJbSGFuZGxlcl0KcHJvY2Vzc0JIYW5kbGVyW0hhbmRsZXJdCnByb2Nlc3NDSGFuZGxlcltIYW5kbGVyXQpwcm9jZXNzREhhbmRsZXJbSGFuZGxlcl0KZW5kCgo)) with problems. I have "Scale to Panel" selected. When my dashboard loads the diagram is cut off like so:

<img width="1238" alt="before" src="https://user-images.githubusercontent.com/33917/33508199-ce10f93c-d6ad-11e7-8481-84f9879c5aa9.png">

but if I then resize the window it is corrected:

<img width="1206" alt="after" src="https://user-images.githubusercontent.com/33917/33508204-d71202d8-d6ad-11e7-88ae-5ffda399540f.png">

**Comment by yanivroz** [comment]
I am also facing the same problem as described here.
When I resize the panel the diagram looks fine in the dashboard for a few seconds until the dashboard is refreshed and then the right side gets chopped off.
any idea?

**Comment by chigui** [comment]
hi,  Any option or work around?

I have the same issue where the diagram scale to panel option is checked and diagram works for some time. After refresh of panel it gets chopped off.

Only happens when the diagram is bigger than the panel.

**Comment by jdbranham** [comment]
Sizing was revamped using flex box - works much better now!
