### ISSUE TITLE
Grafana 4 support

### ISSUE THREAD

**Issue by StianOvrevage** [jdbranham/grafana-diagram#31]
Hi! First of all thanks for an awesome plugin!

I'm having a few issues with my diagrams looking a bit weird and I just upgraded Grafana to the latest beta so I'm wondering if there are anything you have to update in order to make everything look good again on G4?

Br,
Stian

**Comment by jdbranham** [comment]
Thanks @StianOvrevage !
I havent updated to the latest yet, can you paste a screenshot? Or do you see any errors in the browser console?
I'm curious if we'll need a CSS update.

**Comment by StianOvrevage** [comment]
Sure!

Here is my diagram definition:

     graph TB
         subgraph Temp SSD
             /mnt-->tmp-write-bytes[Write bytes]
         end
  
         subgraph Data
             /containers-->bcache0-write-bytes
             /containers-->bcache1-write-bytes
             /containers-->bcache2-write-bytes
             /containers-->bcache3-write-bytes
             /containers-->bcache4-write-bytes
             /containers-->ssdcache-write-bytes
             bcache0-write-bytes-->data1-write-bytes
             bcache1-write-bytes-->data2-write-bytes
             bcache2-write-bytes-->data3-write-bytes
             bcache3-write-bytes-->data4-write-bytes
             bcache4-write-bytes-->data5-write-bytes
         end
  
         subgraph root
             /-->root-write-bytes
         end

Thresholds are set to 0,100,200.

Here is what the diagram looks like:

![grafana4 diagram](https://cloud.githubusercontent.com/assets/6630005/20555879/dee93748-b196-11e6-84f1-afd8ae2fe4be.png)

**Comment by jdbranham** [comment]
Works in 4x and 5x now
