### ISSUE TITLE
Roll Up Checks

### ISSUE THREAD

**Issue by Drabert** [jdbranham/grafana-diagram#32]
Unfortunately i do not own our Grafana deployment so i am not able to add this plugin and test, but i was wondering if a roll-up function was available.  For example, in your diagram, if APP1 was down then have example.com show as Yellow since the service was degraded and if App2 goes down, have it go to orange.  Something like that where you can set a warning/error threshold on a child item that changes the parent items warning/error level.

This looks great though!

**Comment by jdbranham** [comment]
Thanks @Drabert 
For rolling up status, you may like this other plugin I've been working on  -
https://github.com/savantly-net/grafana-heatmap
