### ISSUE TITLE
Can't see values in Firefox

### ISSUE THREAD

**Issue by jmorahan** [jdbranham/grafana-diagram#33]
The values (numbers) don't seem to be appearing under the nodes in Firefox. In Chrome they appear as expected.
Chrome:
![chrome](https://cloud.githubusercontent.com/assets/1612405/20764028/6dd2dfbc-b724-11e6-94a6-8ad205845b0f.png)
Firefox:
![firefox](https://cloud.githubusercontent.com/assets/1612405/20764027/6dd1da68-b724-11e6-8264-07eb5c1af80c.png)
Any idea what could be causing this?
Version 1.3.0, grafana 4.0.0

**Comment by benthorner** [comment]
Also an issue with Internet Explorer (Grafana 3.1.1)...

![capture](https://cloud.githubusercontent.com/assets/9029009/20775069/0ed5fef4-b751-11e6-9d34-2890e23fbdb9.JPG)

**Comment by benthorner** [comment]
Yup, looks like it. Thanks for fixing - happy to wait for the next release :-)

**Comment by volter** [comment]
That release is out: It's 1.4.

**Comment by benthorner** [comment]
Seems to be working in Firefox now, but still not in IE. Appreciate IE isn't nice, but would be really useful if it were supported :-)

**Comment by jdbranham** [comment]
Which version of IE?

**Comment by benthorner** [comment]
I'm using IE 11. Seems to be a problem on earlier versions as well. The above screenshot shows what it looks like in IE 11 with version 1.4 of the plugin: really small and no text.
