### ISSUE TITLE
Values truncated if box label is short in Firefox

### ISSUE THREAD

**Issue by volter** [jdbranham/grafana-diagram#34]
See screenshots! It doesn't look fantastic in Chromium, but the data is visible.
![chromium](https://cloud.githubusercontent.com/assets/1042313/21141756/232f27de-c13f-11e6-824d-acc8f92e36be.png)

![firefox](https://cloud.githubusercontent.com/assets/1042313/21141939/1305166a-c140-11e6-9bc3-ebc81eee2421.png)

**Comment by cpmarvin** [comment]
I have a simmilar issue but with the label text on links. 

![grafana_diagram](https://cloud.githubusercontent.com/assets/20742720/21563720/aa14aad6-ce7c-11e6-913b-6cd45e4baf71.PNG)

Seems the height of the foreignObject is lower than needed for the text to be display corectlly. 

Thx.

**Comment by Nayar** [comment]
![spectacle j11747](https://cloud.githubusercontent.com/assets/454815/23213360/16211e9a-f924-11e6-9570-5109ccd2c153.png)

Same issue here

**Comment by Thor77** [comment]
Same issue here. Any news?

**Comment by jdbranham** [comment]
This was fixed a while back, but I dont have the link to the commit...
