### ISSUE TITLE
Return 0 instead of (null) when select count has no results

### ISSUE THREAD

**Issue by flyingbarron** [jdbranham/grafana-diagram#37]
I'd like to display a metric in a node based on the following query:

`select count(foo) from bar where field = 'value' and time > now() - 1m`

Sometimes there are no results (and that's valid), but the node is blank instead of showing 0.

I assume that something like the single-stat panel's "Value mappings" tab would be a great solution.

**Comment by jdbranham** [comment]
value mappings are available in the plugin now
