### ISSUE TITLE
Feature request: Support Prometheus data source

### ISSUE THREAD

**Issue by RichiH** [jdbranham/grafana-diagram#4]
As per https://github.com/grafana/grafana-plugin-repository/pull/41#issuecomment-251791341

**Comment by RichiH** [comment]
@jdbranham feel free to pop into #prometheus on irc.freenode.net :)

**Comment by jdbranham** [comment]
Done!
Let me know how it works for you.

**Comment by RichiH** [comment]
JFTR, I didn't forget you, I am just too busy atm :(

**Comment by jdbranham** [comment]
no problem.
It seems to be working ok for me now.

**Comment by RichiH** [comment]
This works. Thanks! :)
