### ISSUE TITLE
Mermaid click events

### ISSUE THREAD

**Issue by andrewthad** [jdbranham/grafana-diagram#41]
Mermaid click events (often used for hyperlinking) do not currently work. The fix is simple. Add this line:

    bindEvents(diagramContainer[0]);

right after `diagramContainer.html(...)` gets called in `updateDiagram`.

**Comment by briangann** [comment]
Tried this out, looks like the method name above is incorrect, it should be bindFunctions:

After line 210 in diagramControl.js, add:

bindFunctions(diagramContainer[0]);

I can submit a PR if you like.

**Comment by andrewthad** [comment]
@briangann is right. It's supposed to be `bindFunctions`.

**Comment by FareehaNaaz** [comment]
Hi! i was facing the same issue, and tried adding bindFunctions(diagramContainer[0]); / bindEvents(diagramContainer[0]); in the file diagramControl.js line 210, and 1) restarted grafana and 2) rebuilt package but neither of this helped.

**Comment by rdegez** [comment]
Hi, i'm facing the same issue, adding bindFunctions(diagramContainer[0]) didn't help.
In the grafana dashbord, the diagram is still not clickable when using diagram definiton like:
click XXX "http://xxxx" "link tooltip"

Am I missing something ?

**Comment by njmike** [comment]
I'm experiencing the same behavior - clicking on a link that should be embedded by valid Mermaid syntax does not respond.

I've got Diagram 1.4.0 installed on Grafana v4.5.2

Using example from: https://mermaidjs.github.io/flowchart.html
graph LR;
    A-->B;
    click A callback "Tooltip for a callback"
    click B "http://www.github.com" "This is a tooltip for a link"

Works in the live editor: https://mermaidjs.github.io/mermaid-live-editor/

But not in the diagram plugin.

Thank you in advance, for your time.

**Comment by jag3773** [comment]
Any possibility of getting this fixed in an updated release?

**Comment by jdbranham** [comment]
This works now, but I'm not sure which version fixed it - so unable to link here.

**Comment by jag3773** [comment]
Excellent!  I can verify this works in Grafana v6.2.5 (commit: 6082d19) and grafana-diagram 1.4.4.
