### ISSUE TITLE
Significant figures / decimals in the legend table

### ISSUE THREAD

**Issue by gastoneb** [jdbranham/grafana-diagram#43]
The legend table is difficult to read because it doesn't allow the user to specify the number of decimals that are displayed. For example the difference between 9.6543584132% and 95.695347841% is huge but that isn't obvious from the legend.

The Table plugin has a default number of decimals of 2, which is great.

**Comment by jdbranham** [comment]
v1.7+ of the plugin uses the built-in unit capabilities
