### ISSUE TITLE
Multiple value support?

### ISSUE THREAD

**Issue by dizzythinks** [jdbranham/grafana-diagram#45]
Is it possible to have multiple values on an node? For example, if I have three individual metrics in graphite, 50th, 95th and 99th percentile, I would like to be able to map these three to the same alias node. Is that possible or am I missing something?

**Comment by fabiopbx** [comment]
I've been looking for the exact same thing, my case is upload/download.

**Comment by briangann** [comment]
I submitted in a PR to implement this, you can try it out if you like: https://github.com/jdbranham/grafana-diagram/pull/51

**Comment by jdbranham** [comment]
PR committed
