### ISSUE TITLE
Dynamic Graph Definition

### ISSUE THREAD

**Issue by cproinger** [jdbranham/grafana-diagram#49]
Hello, I have the following enhancement to suggest. 

I use grafana row templates to create a set of rows where each on should contain a diagram. As of now this works as long as each row uses the same diagram. What would be great is if i could create the diagrams dynamically. 

I think either this could work by providing some mapping rules on the selected metrics or one would need to supply the graph-structure with another data-source like the SimpleJson Data-Source plugin. 

If you think that is at all possible, i will try to do this in a fork of this plugin so you can integrate it later. I would be glad if anyone had any ideas on how to realize this.

**Comment by cproinger** [comment]
for me, the easiest way to achieve what i want would be to retrieve the graph-definition from some service instead of specifying it hard coded in the panel. so a graph-definition-url that works with templating would work ...

**Comment by daks** [comment]
I'm facing the same need as @cproinger. In details a haproxy service which generates metrics like

- haproxy-frontend_{foo, bar}
- haproxy-backend_{foo, bar}
- haproxy-server_{foo, bar}

If I could generate the diagram with some regex on those metrics, my Grafana dashboard would be more reusable.

**Comment by jdbranham** [comment]
fixed with https://github.com/jdbranham/grafana-diagram/pull/50
