### ISSUE TITLE
InfluxDB Support

### ISSUE THREAD

**Issue by Gelob** [jdbranham/grafana-diagram#5]
I'd like to help get InfluxDB support working. I have the same ideas as @RichiH with the weathermap type wants he mentioned in the PR on the grafana-plugins repo.

Once thing I'm noticing is that I don't have the Legend options as mentioned in the example pictures. My theory was to get the data displaying in the legend and go from there.

**Comment by jdbranham** [comment]
Sounds great! 
I dont have an InfluxDB service setup currently, and I appreciate any contribution you have.

**Comment by Gelob** [comment]
Do you have any idea why the Legend options wouldn't be displaying, is that something thats hardcoded per data source?

This is what I see
![screen shot 2016-10-07 at 5 00 22 pm](https://cloud.githubusercontent.com/assets/422752/19206599/92ec8ba8-8caf-11e6-9222-182e881adc78.png)

This is what I expect to see
![display](https://raw.githubusercontent.com/jdbranham/grafana-diagram/master/src/img/diagram_display.PNG?raw=true)

**Comment by jdbranham** [comment]
A new version we published a little while ago. Upgrade and see if that works

**Comment by Gelob** [comment]
that fixed that :)

**Comment by jdbranham** [comment]
How about using InfluxDB? Is that also working for you?

**Comment by coussej** [comment]
FWIW: InfluxDB works like a charm in my setup!

**Comment by elvarb** [comment]
It works with InfluxDB but the threshold colorings are not working for me correctly. Regardless of what threshold I set it is not correctly shown in the diagram, if any values are shown it comes as orange/warning

**Comment by jdbranham** [comment]
Great news guys!
Thanks for testing; I'll close this issue now.
