### ISSUE TITLE
Put different thresholds

### ISSUE THREAD

**Issue by jeanduporte** [jdbranham/grafana-diagram#52]
Hello,

I have a problem with the panel "Diagram", I want to put different thresholds on my series of data. But in the tabs "Series specific overrides" it doesn't work when I want to select one of my series by it alias. Even when I write it.

Here it is an example from the help of Grafana, this is what I want :

![628f21a73c5d09bc6ffe594e13c0309c2fbf87e5_1_690x416](https://cloud.githubusercontent.com/assets/28293036/25611004/bf2510dc-2f25-11e7-92bd-c294b8d016cf.png)

Any ideas? Something I did wrong?

**Comment by jdbranham** [comment]
Hi @jeanduporte 
You may check the 'legend' of your graph to see if the alias you are entering matches the labels there.

**Comment by jeanduporte** [comment]
Hi @jdbranham I checked the legend of the graph and the alias appears in the legend, but impossible to select it in "Series specific overrides".

**Comment by jdbranham** [comment]
Hi @jeanduporte 
I know it's been a long time, but I'm following up on open issues.
Have you updated the plugin version? And/or still seeing this issue?

Thanks!

**Comment by jeanduporte** [comment]
Hi @jdbranham 
I didn't try to use the panel since that time. I try it this week to see if it works or not to close the issue (or not).

**Comment by jdbranham** [comment]
v1.7+ of the plugin improves metric selection and renaming.
