### ISSUE TITLE
Composites don't seem to display the correct metric name against the value

### ISSUE THREAD

**Issue by divishkumar** [jdbranham/grafana-diagram#53]
With composites, it doesn't seem to display the correct metric name against the value. (I've noticed it always shows the name of the last added metric to the composite's metric list)

![image](https://cloud.githubusercontent.com/assets/27893565/26285164/38c78c1e-3e42-11e7-8a7e-e66bad54e421.png)

as seen from the above, its displaying the app-children value as app-cpu.

Also, are we able to display static text and a metric value on links like we can with nodes ? In the above example, I'd like to display the name of the request and the time its taking on the link.

**Comment by Finkregh** [comment]
I suppose i have the same feature-request, i get a string as value and would like to show that in a node...

**Comment by briangann** [comment]
Definitely a bug there - I'll submit a PR for it.

For the second question - yes you can display text along with a value on a link, like this, which reminds me to implement unit formatting on the link values :)

![image](https://user-images.githubusercontent.com/7364245/32407429-d046c518-c156-11e7-9d16-1cb8bb093808.png)

![image](https://user-images.githubusercontent.com/7364245/32407430-d7a0061c-c156-11e7-84aa-7fc6c89ce552.png)

**Comment by divishkumar** [comment]
Perfect. Thanks @briangann
