### ISSUE TITLE
Feature: allow to override unit format

### ISSUE THREAD

**Issue by gentunian** [jdbranham/grafana-diagram#55]
Override allows you to change threshold, colors and which value to use (avg, min, max, etc) but won't allow you to change the unit. I know that it may be a nonsense as you may show a diagram showing specific metric for each node (or server).

But diagrams can be extended to be abstract things and nodes may be things that are related to other nodes that could be metrics instead of server. For example, a node may be a server and could have relation with its metrics, say server A has a CPU metric and HEAP metric. Both, CPU and HEAP may be nodes of server A. It's not a workflow though, it may be a graph.

**Comment by shashilpikrishan** [comment]
Same problem here i.e. while developing service maps for two different dependent application layers we see the same issue as one layer emits in milliseconds & other in microseconds.

**Comment by mirath** [comment]
+1

**Comment by mirath** [comment]
For me. I have graphs with the percentage of queries that take more than N seconds to complete, but I would like to add a line on top of that graph that shows the raw volume of queries, so I can have an idea of the magnitude that that percentage represents

**Comment by jdbranham** [comment]
This feature is available in the latest version

**Comment by MarcusCaepio** [comment]
Which version is this?
I have ii  grafana                               5.2.2                                      amd64        Grafana
and cannot find it

**Comment by jdbranham** [comment]
Hi @MarcusCaepio 
I'm working through any outstanding issues.
Are you still having a problem with this?

**Comment by MarcusCaepio** [comment]
Well, an answer to my last question would be nice :D

**Comment by sergeyberezansky** [comment]
Hello, I am also a big +1 for this
Consider another scenario: having lots of metrics, part are percentages, another part raw values of different types (throughputs, storage units, raw counts etc)
Making a repeating panel for all those metrics - and want to define a single series override on the panel, that will automatically choose the right units based on field name

**Comment by jdbranham** [comment]
Unit override available in v1.7+ of the plugin
