### ISSUE TITLE
Color of nodes only updated after first refresh interval elapses

### ISSUE THREAD

**Issue by ghost** [jdbranham/grafana-diagram#56]
Hello everyone,

First of all, thanks for the great plugin. It's amazing and super easy to work with!

As I've been working with the plugin, I've found an issue that's been causing some pain. The node colors are only updated after the first refresh interval. Each subsequent interval also triggers the update of the node colors. However, if I do not have the dashboard configured to update periodically, the node colors never change from the default light green.

This is also effecting my ability to embed images of the diagram in our documentation. Since the image generated by Grafana does not show any of the actual node colors (according to the rules I setup) since no update is being triggered on the back-end, the nodes are all light green.

I would expect that the metric data that determines the node colors would be updated on page load, as well as when the frequency timer elapses. Perhaps it's not the metric data necessarily, but something in the diagram library which is only being triggered on the update interval.

In any case, I thought I'd report the bug since I like the project so much. If there is anything I can do to help, feel free to let me know.

Thanks everyone,

Christopher

**Comment by somatronicon** [comment]
Hi everyone, I was messing with the image URL for a diagram and found that if I set the refresh attribute to 1ms it was able to load the metrics and update the node colors.

`refresh=1ms`

So, the complete image URL looked like:

https://metrics.mydomain.local/render/dashboard-solo/db/test?refresh=1ms&panelId=1&orgId=1&tab=display&from=now-1h&to=now&theme=light&tz=UTC-05%3A00

**Comment by sawo1337** [comment]
Thanks for pointing the issue out, I was also looking why the data is not pulled from the datasource until I edit it manually. I don't think refresh interval of 1ms is good, it will put tremendous strain on some datasources, but I do use autorefresh, so that solves the issue for me.

**Comment by kedare** [comment]
Any way to use this when using dashboard playlists ? Looks like we cannot push refresh=1ms
