### ISSUE TITLE
Treshold limit to three?

### ISSUE THREAD

**Issue by coussej** [jdbranham/grafana-diagram#6]
First of all: GREAT IDEA! Lots of use cases for this plugin!

I was wondering, for the diagram color changing, are you limited to the 3 levels provided by the grafana tresholds or is there some way to expand this to more levels? I'm looking to create a real time view on a production line with more then three statusses.

**Comment by jdbranham** [comment]
We can do more than 3 levels.
I originally copied the threshold code from the graph plugin, but it shouldn't be difficult to modify.
I could also use more then 3 on my main use case.
I'll commit a change soon with threshold modifications.
Thanks for checking this out, and the feedback!

**Comment by jdbranham** [comment]
New feature added.
