### ISSUE TITLE
How to adjust node or nodelink position on the diagram?

### ISSUE THREAD

**Issue by satishdhavan** [jdbranham/grafana-diagram#60]
Hello Contributors,

I am building some interesting flow charts in Grafana diagram panel using mermaid JS syntax.

I just have one issue on how to adjust the position of nodes I created in the graph.

I tired styling the nodes and node links but styling is not useful to adjust the position of a node.

Please help me on this.

Attached is the file u wanna look into.

where I want to adjust the positions of Avg Rate and Errros nodes to whereever I want.

[AACC-mermaid-Syntax.txt](https://github.com/jdbranham/grafana-diagram/files/1201063/AACC-mermaid-Syntax.txt)

**Comment by jdbranham** [comment]
Hi @satishdhavan 
I'm following up on old issues and noticed this one!
We fixed the sizing issue in the latest release; it might have solved your issue.

![image](https://user-images.githubusercontent.com/2660839/60750778-4dfd1d80-9f73-11e9-909c-8e0d210983a7.png)

**Comment by NobleVision** [comment]
Grafana 7.0 fixed the spacing issue, but did not fix values given to the text in the lines between the boxes.

**Comment by jdbranham** [comment]
v1.7+ of the plugin fixes the UI issues, and allows custom CSS to be used per diagram.
