### ISSUE TITLE
ETA on release of "Metric Composites" feature (ie version 1.4.1) to the grafana repo ?  Latest is 1.4.0

### ISSUE THREAD

**Issue by khenness** [jdbranham/grafana-diagram#61]
Hi,

We are using this plugin in my workplace and we were hoping to use the "Metric Composites" functionality: https://github.com/jdbranham/grafana-diagram/blob/master/dist/img/composite-editor-tab.png

We noticed that this is included in version 1.4.1 in github: https://github.com/jdbranham/grafana-diagram/blob/master/package.json however the highest version available in the grafana repos is 1.4.0: https://grafana.com/plugins/jdbranham-diagram-panel

We were wondering if it would be possible for you to update the grafana repo with the lastest version that includes this functionality? Or do you have an ETA when this will be released? 

Thanks,
Kevin

**Comment by cantayma** [comment]
Good afternoon, 

I would also like to use "Metric Composites". When will it be available?

Thanks,
Candice

**Comment by khenness** [comment]
Any thoughts on this @jdbranham ?

**Comment by jdbranham** [comment]
Sorry for the delay!
Been swamped the last few months. I'm working on the merges now and hope to have the new version submitted later today.

**Comment by jdbranham** [comment]
https://github.com/grafana/grafana-plugin-repository/pull/191

**Comment by cantayma** [comment]
Fantastic! Thanks a lot.

-Candice Marquart

**Comment by khenness** [comment]
Thanks, much appreciated!

**Comment by khenness** [comment]
Hey @jdbranham 

I was just trying to install the plugin and I cannot find a version past 1.4.0.

I am not seeing anything past version 1.4.0 on this page: https://grafana.com/plugins/jdbranham-diagram-panel/installation

And when I log into one of our Grafana hosts and do _grafana-cli plugins list-remote_ I can only see this being available: _id: jdbranham-diagram-panel version: 1.4.0_.

Did you definitely upload the new version correctly?

**Comment by khenness** [comment]
Oh sorry I see that your PR has not been merged yet, nevermind!

**Comment by jdbranham** [comment]
There was a bug in the plugin.json in the last publish.
It should be resolved when this PR is merged - https://github.com/grafana/grafana-plugin-repository/pull/193

**Comment by jdbranham** [comment]
PR merged!
