### ISSUE TITLE
Support prefix modifier

### ISSUE THREAD

**Issue by M4t3o** [jdbranham/grafana-diagram#63]
Hi
I'd like to use prefix modifier as documented here : https://github.com/jdbranham/grafana-diagram#prefix-modifier-for-series.

My context : 
- grafana 4.3.1
- diagram plugin 1.4.0
- datasource influxDB

Exemple : 
<code>A{LB} -->|"@bandwidth_web1"|web1</code>

Metric is displayed but the alias is not hidden.

Others good features but someone have already asked for it:
- override units per serie regex :)
- click function (https://mermaidjs.github.io/flowchart.html)

Thanks for this usefull plugin.
Regards.

**Comment by jdbranham** [comment]
These features will be available as soon as the PR has been merged - 
https://github.com/grafana/grafana-plugin-repository/pull/191
