### ISSUE TITLE
How to open new window/page on click of diagram box in Grafana

### ISSUE THREAD

**Issue by arifA9** [jdbranham/grafana-diagram#65]
I am trying to open the new page from Grafana dashboard.

I am using diagram plugin to develop the dashboard and using mermaid, i have sequence of workflow, on click of one of the box, i would like to open the new page.

Need support and help.
![image](https://user-images.githubusercontent.com/32505944/31335249-5c8662ec-ad0f-11e7-9cea-4e1ec57ec01d.png)

**Comment by jdbranham** [comment]
yes, you can embed html links in your mermaid definition. 
For example - 

```
graph TB
Web1 ==> App1
Web2 --> App1
App1 --> DB-Node1("<a href='http://google.com'>google</a>")
```

Could render something like this (notice the link)  

![image](https://user-images.githubusercontent.com/2660839/32909950-9f3511de-cacd-11e7-9586-be70c0da011f.png)

**Comment by jdbranham** [comment]
Also, Mermaid has support for embedded a link without html, in the form of a click handler.
In the subsection "Interaction" you may find more information -
https://mermaidjs.github.io/flowchart.html  

```
graph LR;
    A-->B;
    click A callback "Tooltip for a callback"
    click B "http://www.github.com" "This is a tooltip for a link"
```

**Comment by matletix** [comment]
Link given by @jdbranham got broken, here's a new link:
https://mermaid-js.github.io/mermaid/diagrams-and-syntax-and-examples/flowchart.html#interaction
