### ISSUE TITLE
Problem with Azure Monitor (App Insights) Metrics

### ISSUE THREAD

**Issue by NicolaiPetri** [jdbranham/grafana-diagram#66]
Currently it's not possible to user Application Insights metrics in diagram because of naming problems.
Example naming for a metric:
`dependencies/duration{dependency/target="tcp:somesqlserver.database.windows.net,1433 | mysqldatabase"}`

I suggest changing replace RegEx in diagramControl.js from 
`/"\\|||,|;|=|:|{|}/g`

to

`/\||\/| |"|,|;|=|:|{|}/g`

I think this should work. Maybe just strip spaces instead of replacing them with '_'

**Comment by NicolaiPetri** [comment]
And it seems that using Azure Monitor datasource plugin makes atleast versions of plugin in git fail hard. When using prometheus, at least it doesn't fail, but there are no metrics on the diagrams at all ? Can anyone else see this issue? using #syntax metrics can be displayed on diagram, so data is there.

**Comment by daniellee** [comment]
@NicolaiPetri the latest version (0.0.8) of the Azure Monitor plugin added an alias feature so that you can format the metric name any way you want.

**Comment by NicolaiPetri** [comment]
@daniellee I can see the benefit of doing this, but unfortunate some of the Application Insights metrics contains both spaces and pipes (|) so it doesn't solve my problem :( 
I don't really believe it's (only) a problem with the Azure Datasource, but more a direct problem for this diagram panel. It should atleast replace spaces and pipes with _ as it does with other unsupported characters.

**Comment by jdbranham** [comment]
enhanced metric renaming added in v1.7.3
