### ISSUE TITLE
Current git version seems broken

### ISSUE THREAD

**Issue by NicolaiPetri** [jdbranham/grafana-diagram#67]
No metrics are displayed when using latest version from git. 
I would love to try to fix this, but it might be easier with a little insight on why it might have stopped working ?
@jdbranham I know you most likely are busy with other stuff, but maybe you can somehow help me and/or other developers with continuing your great work ?

**Comment by briangann** [comment]
It's definitely bugged, I'm working on a fix, will have a PR today. 

The first bug is a wayward { at line 227 in diagramControl.js, but I'm seeing a couple of other issues besides that.

**Comment by NicolaiPetri** [comment]
You are my hero :)
I'm testing with Prometheus and Azure Monitor data source. 
I have also seen issues where it fails with exception where .Replace is called on a null object. I have not been able to identify root cause yet as I don't fully understand the code flow.
But I suspect that it might be related to clearing values before doing new update.
If you need help for testing or other information don't hesitate to write me. You can find me at nicolai (aa) petri (d0t) dk or nicolaipetri (skype)
