### ISSUE TITLE
Automate file map creation outside of Grafana

### ISSUE THREAD

**Issue by talbaror** [jdbranham/grafana-diagram#68]
Hi,
Is there a way to automatically create file mermaid syntax by my own script and  use it in Grafana?

Thanks

**Comment by jdbranham** [comment]
You may be able to use the 'url' feature - 

![image](https://user-images.githubusercontent.com/2660839/32909000-f414ec68-caca-11e7-86d8-cf6d0ef220fd.png)


You could also generate the mermaid file in real-time on the server using nodejs, .net, java, etc...
