### ISSUE TITLE
unknown panel type

### ISSUE THREAD

**Issue by nimeops** [jdbranham/grafana-diagram#72]
Hi, 
since upgraded, no diagram plugins available.

Grafana version: 4.6.2

![image](https://user-images.githubusercontent.com/7293261/33039772-70ac44f8-ce39-11e7-9ecb-e28f3fdba31f.png)

**Comment by msteggink** [comment]
Can you check grafana.ini for the plugins directive?
;plugins = /var/lib/grafana/plugins
And the permissions in that directory?

**Comment by yisraelU** [comment]
i also get an unknown panel type error for the same reason as above json: cannot unmarshal string into Go struct field PluginInfo.author of type plugins.PluginInfoLink"

**Comment by jdbranham** [comment]
https://github.com/grafana/grafana-plugin-repository/pull/193

Waiting for this pr to be merged and the issue will be resolved.

**Comment by jdbranham** [comment]
You can clone this repository into your local diagram plug-in folder if you don't want to wait for the pr

**Comment by jdbranham** [comment]
#70

**Comment by jdbranham** [comment]
PR merged!
