### ISSUE TITLE
[Question] change default style

### ISSUE THREAD

**Issue by MarcMagnin** [jdbranham/grafana-diagram#73]
Hi,

Thanks for that plugin!
I'd like to know if that's possible to change the default green color or, when a serie has no value, do a value mapping ie from null to 0 for instance.
Many thanks,
Marc

**Comment by jdbranham** [comment]
Hi @MarcMagnin 
Which Datasource do you use?

**Comment by MarcMagnin** [comment]
hey! 
Prometheus.

**Comment by jdbranham** [comment]
Good idea for enhancement.  
Opened #76 

You may also consider the 'or' operator in your query until this is implemented.
https://prometheus.io/docs/prometheus/latest/querying/operators/#logical-set-binary-operators
