### ISSUE TITLE
1.4.3 Doesn't work in docker

### ISSUE THREAD

**Issue by pdu-avaleo** [jdbranham/grafana-diagram#74]
```
docker run -it -e "GF_INSTALL_PLUGINS=jdbranham-diagram-panel" grafana/grafana:4.6.2
```

results with:
```
Plugins: Failed to load plugin json file: /var/lib/grafana/plugins/jdbranham-diagram-panel/dist/plugin.json,  err: json: cannot unmarshal string into Go struct field PluginInfo.author of type plugins.PluginInfoLink
```

**Comment by antineutron** [comment]
Can confirm it doesn't load on 4.6.2 outside of docker (installed from packagecloud repo on ubuntu 16.04).

Looking at other plugins in the directory, the author field format changed from a string to a hash. Hopefully a quick fix!

**Comment by dynek** [comment]
1.4.4 seems to fix this (see https://github.com/jdbranham/grafana-diagram/commit/91dd3a6fd84f8a4265d12f60b13219d29242bb41) but do not seem to understand when it will be available from grafana.com

**Comment by jdbranham** [comment]
Should be resolved when this PR is merged - https://github.com/grafana/grafana-plugin-repository/pull/193

**Comment by jdbranham** [comment]
PR Merged!
