### ISSUE TITLE
How to change the color of time string or title when adding GANTT diagram functionality to mermaid

### ISSUE THREAD

**Issue by carsonzhu** [jdbranham/grafana-diagram#77]
See the screenshot below,
![image](https://user-images.githubusercontent.com/13717755/33640118-9f94dae6-da69-11e7-8db4-e8c04bd36d0c.png)

The black time string and title is almost invisible, maybe white is a better color choice. But I can't find the place to change the color, who can help me?

**Comment by jag3773** [comment]
We have the same issue...

**Comment by dsm888** [comment]
Hi i am new to using this panel. can you give more info on how to write the mermaid syntax or what to do to display gantt chart display

**Comment by jdbranham** [comment]
CSS support is now available in the graph definition
Example - 
```
graph LR
    id1(Start)-->id2(Stop)
    style id1 fill:#f9f,stroke:#333,stroke-width:4px
    style id2 fill:#ccf,stroke:#f66,stroke-width:2px,stroke-dasharray: 5, 5
```

**Comment by jdbranham** [comment]
Added a 'custom styles' section -

![image](https://user-images.githubusercontent.com/2660839/60747972-06649a80-9f4f-11e9-8767-27b6bce8554d.png)

**Comment by carsonzhu** [comment]
@jdbranham Thanks for your reply!
