### ISSUE TITLE
Scale diagram to panel size

### ISSUE THREAD

**Issue by coussej** [jdbranham/grafana-diagram#8]
I'm looking for a way to model a production line and make the machines change color based on their status. This plugin fits my use, but I have a 'small' problem: you currently cannot increase the size of the diagrams. Would it be hard to add a feature so that the diagram scales with the size of the panel? 
I checked the mermaid docs to try and increase the size of the individual blocks, but if you change the size with css style (width, height) it messes up the diagram.

**Comment by jdbranham** [comment]
Thanks @coussej , I've been considering this.
It will be in the next release.

**Comment by jdbranham** [comment]
It was easier than I thought.
I'll commit the change later today

**Comment by coussej** [comment]
Thanks a lot!

**Comment by OnepieceLC** [comment]
Then，how can I resize my panel ?
