### ISSUE TITLE
templating (use variables) in Diagram Definition URL

### ISSUE THREAD

**Issue by anatoliegolovco** [jdbranham/grafana-diagram#83]
Hi, thanks for plugin

Is it feasible to have templating  in Diagram Definition URL? as feature request

I was tried, but it doesn't interpret the variable:

```
https://domain.com/graph/?q="$house_id"
https://domain.com/graph/?q=$house_id
```

**Comment by nickman** [comment]
It works for me, except without the quotes. e.g.
**http://localhost:7070/instance/$stat/$instance/$cluster/$ds**
