### ISSUE TITLE
diagram support Mysql datasource?

### ISSUE THREAD

**Issue by xiaoxuan220** [jdbranham/grafana-diagram#84]
Grafana v4.6.2 
diagram:1.4.4
I want to know,Support mysql datasource?
If support,where can i find some document or examples
Thanks very much!

**Comment by nharthing** [comment]
@xiaoxuan220 : Diagram seems to work with MySQL datasource. I was able to select MySQL datasource and Diagram plugin seems to interpret it just fine generally. (Caveat: I am receiving some sort of error when the values returned are all zeroes; not sure if this is a feature of Diagram or just my query being incorrect.)

I wasn't able to find documentation specifically for using Diagram with Grafana, where MySQL is the datasource. 

_Time Series Query default looks like this_, but you'd need to plug in your own values:
SELECT
  UNIX_TIMESTAMP(<time_column>) as time_sec,
  <value column> as value,
  <series name column> as metric
FROM <table name>
WHERE $__timeFilter(time_column)
ORDER BY <time_column> ASC

Biggest learning curve for me was realizing the definition of the item (example: A) has to match the metric from the query results. 

_Default graph script syntax:_ 
graph LR
A[Square Rect] -- Link text --> B((Circle))
A --> C(Round Rect)
B --> D{Rhombus}
C --> D

Mermaid syntax: [](https://mermaidjs.github.io/flowchart.html)

**Comment by adeverteuil** [comment]
Thanks @nharthing.

Just to make it a little more clear and explicit:

```
SELECT
    […] as value,
    'this_would_be_the_diagram_node_name' as metric
```

Relevant documentation:

> You may return a column named `metric` that is used as metric name for the value column.

Source: https://grafana.com/docs/features/datasources/mysql/#time-series-queries
