### ISSUE TITLE
can pass templated variables to URL but how to pass current dash timerange

### ISSUE THREAD

**Issue by steveh999** [jdbranham/grafana-diagram#85]
Firstly thanks for an excellent panel, it's extremely useful

I have been using it for a while with static diagrams but now I am writing an external web service to return a mermaid response but altho  the templated variables are expanded in the URL created, for example : 

http://amazon-trdc/my_service/$peercountry/$source/$target

becomes : 
 /my_service/{au,de,hk,us}/{amazon-iclient-sydney}/{centos.brisanet.com.br}

I have no idea how to pass the timerange of the dashboard

Searching the issues list etc yields no answer to this question. Is this actually possible ?? Any pointers would be greatly appreciated

Many Thanks

Steve

**Comment by ben-turner** [comment]
This is handled by Grafana itself rather than the diagram panel. In the [Grafana Documentation](http://docs.grafana.org/reference/templating/#the-timefilter-or-timefilter-variable) it says there is a built in variable called `$__timeFilter` that should do what you need.

**Comment by shivam-bidgely** [comment]
@ben-turner that doesn't work. It isn't replacing the variable and is parsing it as a literal.

**Comment by Alice2222** [comment]
modify the DiagramController.tsx's code. use 'this.props.replaceVariables' to parsed variables.
![image](https://user-images.githubusercontent.com/21191777/109496403-9152bb00-7acb-11eb-8d13-4a852f1e714b.png)
