### ISSUE TITLE
Diagram Keeps Adding Value Nodes When Definition URL Does Not Respond

### ISSUE THREAD

**Issue by nickman** [jdbranham/grafana-diagram#89]
If the endpoint supplying the diagram definition stops responding, the diagram keeps adding value nodes. For example:
![image](https://user-images.githubusercontent.com/597608/39060086-59f5a45e-448e-11e8-8d5a-bfea79ab6ba8.png)
However, once the endpoint starts responding again, the nodes are cleared up:
![image](https://user-images.githubusercontent.com/597608/39060134-8465cab6-448e-11e8-8f6b-384cb36a934d.png)

**Comment by jdbranham** [comment]
This should be handled correctly in v1.7+
