### ISSUE TITLE
Documentation: How can I apply a metric to an edge as opposed to a node

### ISSUE THREAD

**Issue by RichiH** [jdbranham/grafana-diagram#9]
I can trivially add `_my_prom_query_[name] -> foo`, but I am unclear how to do this for the actuel edge/arrow connecting the two.

**Comment by jdbranham** [comment]
You can label the connectors like this -

_my_prom_query_[name] --bar--> foo

**Comment by RichiH** [comment]
Can I also do `bar --my_prom_query[name]--> foo`? Can't test atm :/

**Comment by jdbranham** [comment]
Unfortunately that fails, but maybe we can fix this using dashboard variables...

**Comment by RichiH** [comment]
@jdbranham Any chance that you'll tackle this? I could _really_ use this this weekend for FOSDEM. :)

**Comment by RichiH** [comment]
And I will give you screenshots for your girlfriend ;)

**Comment by RichiH** [comment]
And, as a follow-up, having a bidirectional arrow would be even better.

**Comment by jdbranham** [comment]
Closing old issues - we fixed this but I don't remember when =]

**Comment by jdbranham** [comment]
> And I will give you screenshots for your girlfriend ;)

I think she finally realized I wasnt wasting my time working on OSS =]
