### ISSUE TITLE
Unable to successfully retrieve data using diagram definition URL

### ISSUE THREAD

**Issue by ozbrarb** [jdbranham/grafana-diagram#90]
I've setup an IIS server and also a stand-alone Python server but have been unsuccessful in getting the data as mermaid syntax to show in the panel. Entering the same data in the Content section works fine. 

What is required to get the URL to work?

**Comment by ben-turner** [comment]
What version of the plugin are you running?

What Grafana version are you running?

Are there any errors (check your browser dev tools)?

Can you show the mermaid output you generated (if it isn't too long)?

**Comment by andyclegg** [comment]
I'm having a similar problem.
The URL I'm setting is http://localhost:5000/diagram (a custom Flask app)

The app works, the data is returned correctly (as text/plain) and works fine if pasted into the 'Content' section:
```
$ curl -v http://localhost:5000/diagram
*   Trying ::1...
* TCP_NODELAY set
* connect to ::1 port 5000 failed: Connection refused
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 5000 (#0)
> GET /diagram HTTP/1.1
> Host: localhost:5000
> User-Agent: curl/7.52.1
> Accept: */*
> 
* HTTP 1.0, assume close after body
< HTTP/1.0 200 OK
< Content-Type: text/plain; charset=utf-8
< Content-Length: 119
< Server: Werkzeug/0.14.1 Python/2.7.15
< Date: Thu, 12 Jul 2018 14:00:27 GMT
< 
graph TD
status_lets_go --> |slowjob|status_slowjob_success
status_slowjob_success --> |cleanup|status_cleanup_success
* Curl_http_done: called premature == 0
* Closing connection 0
```
However looking in the Chrome developer console, it appears that the URL requested has the 'http' stripped and this is disallowed:
```
VM38:1 Failed to load localhost:5000/diagram: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.
```

**Comment by docinfosci** [comment]
The responding service needs to return an access control header granting the requesting domain permission to display the data in the browser.  For example: 

```
# A Python AWS Lambda HTTP mapped service responds to Grafana...
return {
        'statusCode': 200,
        'headers': {
            'Content-Type': 'text/plain',
            'Access-Control-Allow-Origin': 'http://localhost:3000',
        },
        'body': data,
    }
```

Where http://localhost:3000 is a locally installed Grafana calling an AWS Lambda HTTPS mapped service providing the data.

You might find this [Stackflow discussion](https://stackoverflow.com/questions/10636611/how-does-access-control-allow-origin-header-work) interesting.

Have a great day!
