### ISSUE TITLE
Grafana Diagram issue with linkStyle colors for lines

### ISSUE THREAD

**Issue by fchiorascu** [jdbranham/grafana-diagram#93]
Hi,

I've tried a simulation on: Mermaid Live Editor and it works fine/ perfect but when I'm going in Grafana Dashboard using Diagram the colors for lines will not apply.

```
graph TD
A[0] --> D{Px01}
G[2] --> D{Px01}
H[1] --> D{Px01}
D{Px01} --> J(3)
A[0] --> E{Px02}
G[2] --> E{Px02}
H[1] --> E{Px02}
E{Px02}--> J(3)

linkStyle 3 stroke-width:2px,fill:none,stroke:blue;
linkStyle 7 stroke-width:2px,fill:none,stroke:orange;
```

Kind Regards,

**Comment by samard** [comment]
Hi team,

did anyone found the resolution?? kindly update.
I am also facing same issue, in grafana v5.3.4.
My mermaid syntax is correct, as I can see the changes in "linestyle "reflecting in Mermaid live editor but not in my Grafana dashboard.
Let me know any workaround or resolution steps.

Regards.

**Comment by samard** [comment]
> Hi,
> 
> I've tried a simulation on: Mermaid Live Editor and it works fine/ perfect but when I'm going in Grafana Dashboard using Diagram the colors for lines will not apply.
> 
> ```
> graph TD
> A[0] --> D{Px01}
> G[2] --> D{Px01}
> H[1] --> D{Px01}
> D{Px01} --> J(3)
> A[0] --> E{Px02}
> G[2] --> E{Px02}
> H[1] --> E{Px02}
> E{Px02}--> J(3)
> 
> linkStyle 3 stroke-width:2px,fill:none,stroke:blue;
> linkStyle 7 stroke-width:2px,fill:none,stroke:orange;
> ```
> Kind Regards,

@fchiorascu did you happen to resolve the issue of linkstyle color? can you share it here, if solved.

**Comment by samard** [comment]
> Hi team,
> 
> did anyone found the resolution?? kindly update.
> I am also facing same issue, in grafana v5.3.4.
> My mermaid syntax is correct, as I can see the changes in "linkstyle "reflecting in Mermaid live editor but not in my Grafana dashboard.
> Let me know any workaround or resolution steps.
> 
> Regards.

Hi @briangann can you help me with this bug.

**Comment by briangann** [comment]
i'll take a look at it

**Comment by samard** [comment]
> i'll take a look at it

Thanks, let me know if you need any other info.

**Comment by robincw-gr** [comment]
It's because the green color is !important in the css. This has been done to apply it to links between subgraphs, otherwise they are black. The css is messy; !important should not be used. You would have to have !important after your color to override it but the ! is rejected by the Mermaid parser.

**Comment by Dylantje** [comment]
Perhaps possible to change the line colors, @ this moment?
Or perhaps with ccs?
Likt have red and bleu lines

**Comment by jdbranham** [comment]
I removed all the custom css so we can leverage the mermaid js theme support.

![image](https://user-images.githubusercontent.com/2660839/79726309-34358880-82b0-11ea-90c7-0f2ad64a01c5.png)

The embedded styles are also supported now - 
![image](https://user-images.githubusercontent.com/2660839/79726436-68a94480-82b0-11ea-9d5c-0f60a046e0f5.png)
