### ISSUE TITLE
Diagram size is screwed up after refreshing

### ISSUE THREAD

**Issue by maresende** [jdbranham/grafana-diagram#96]
When a diagram is very big (bigger than the screen size) and I need to select the "scale to panel" option, I lost the new scaled size every time my diagram refreshes....

The workaround to me was to set false in this section of panel's json:

 "flowchart": {
      "htmlLabels": true,
      **"useMaxWidth": false**
}

**Comment by dmayan** [comment]
This solved it for me also, thanks
