### ISSUE TITLE
Return screenshot with empty value by using Grafana API

### ISSUE THREAD

**Issue by mill9r** [jdbranham/grafana-diagram#97]
I'm trying to getting screenshots by using Grafana API, but I get only flowchart without value. How can I solve this problem? Grafana ver. 5.1.1.

**Comment by mill9r** [comment]
Grafana version 5.1.1

**Comment by m-a-leclercq** [comment]
This plugin seems to be broken for Grafana 5.X

See https://github.com/jdbranham/grafana-diagram/issues/87

**Comment by jdbranham** [comment]
Resolved in v1.4.5
