### ISSUE TITLE
Sankey diagram

### ISSUE THREAD

**Issue by simPod** [jdbranham/grafana-diagram#98]
Hello, can this do Sankey diagram? Something like 

![image](https://user-images.githubusercontent.com/327717/43306302-5b49b70e-9183-11e8-90a4-07e3325322b8.png)

Thanks

**Comment by jdbranham** [comment]
Hi @simPod 
It doesn't produce this style of diagram, but that would be an interesting new project!

**Comment by simPod** [comment]
Thanks for reply!
